In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [95]:
pd.read_csv('../capas_def/MRI.csv')

,RID,CEREB_TCV,CEREB_TCB,CEREB_TCC,CEREB_GRAY,CEREB_WHITE,L_HIPPO,R_HIPPO,TOTAL_HIPPO,TOTAL_CSF,TOTAL_GRAY,TOTAL_WHITE,TBM_1,TBM_2,IPCA1,IPCA2,LHIPPO,RHIPPO,ST111_CV,ST111_SA,ST111_TA,ST111_TS,ST115_CV,ST115_SA,ST115_TA,ST115_TS,ST116_CV,ST116_SA,ST116_TA,ST116_TS,ST118_CV,ST118_SA,ST118_TA,ST118_TS,ST119_CV,ST119_SA,ST119_TA,ST119_TS,ST24_CV,ST24_SA,ST24_TA,ST24_TS,ST26_CV,ST26_SA,ST26_TA,ST26_TS,ST31_CV,ST31_SA,ST31_TA,ST31_TS,ST32_CV,ST32_SA,ST32_TA,ST32_TS,ST40_CV,ST40_SA,ST40_TA,ST40_TS,ST52_CV,ST52_SA,ST52_TA,ST52_TS,ST55_CV,ST55_SA,ST55_TA,ST55_TS,ST56_CV,ST56_SA,ST56_TA,ST56_TS,ST57_CV,ST57_SA,ST57_TA,ST57_TS,ST59_CV,ST59_SA,ST59_TA,ST59_TS,ST60_CV,ST60_SA,ST60_TA,ST60_TS,ST74_CV,ST74_SA,ST74_TA,ST74_TS,ST83_CV,ST83_SA,ST83_TA,ST83_TS,ST85_CV,ST85_SA,ST85_TA,ST85_TS,ST90_CV,ST90_SA,ST90_TA,ST90_TS,ST91_CV,ST91_SA,ST91_TA,ST91_TS,ST99_CV,ST99_SA,ST99_TA,ST99_TS
0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8856.0,3886.0,2.211,0.658,23577.0,8209.0,2.691,0.720,13054.0,6010.0,2.017,0.650,8892.0,3521.0,2.279,0.787,1765.0,297.0,3.904,0.658,2241.0,507.0,3.254,1.022,9307.0,3116.0,2.561,0.784,12035.0,4802.0,2.301,0.557,12098.0,3669.0,2.779,0.727,12253.0,3587.0,2.795,0.740,8319.0,3795.0,2.166,0.579,18039.0,7100.0,2.318,0.644,23583.0,7984.0,2.655,0.697,13753.0,6196.0,2.077,0.648,9924.0,3866.0,2.446,0.551,1635.0,355.0,3.236,0.684,6566.0,2600.0,2.363,0.736,1936.0,320.0,3.610,0.925,7252.0,2418.0,2.727,0.724,15789.0,6612.0,2.243,0.650,11155.0,3273.0,2.901,0.688,15683.0,4272.0,3.028,0.649
1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,978.439,992.628,0.317268,NaN,1698.17,1419.86,8112.0,3721.0,2.052,0.561,20473.0,7458.0,2.426,0.721,10405.0,4807.0,1.920,0.597,9424.0,3717.0,2.289,0.657,1341.0,309.0,2.964,0.677,806.0,370.0,1.805,0.815,7501.0,2911.0,2.234,0.727,8558.0,3657.0,2.102,0.567,9008.0,3226.0,2.348,0.683,8035.0,2698.0,2.453,0.685,7922.0,3560.0,2.051,0.591,15602.0,6725.0,2.026,0.646,21166.0,7397.0,2.494,0.696,11181.0,4988.0,2.033,0.601,9988.0,3819.0,2.321,0.563,1813.0,355.0,3.574,0.786,4833.0,1948.0,2.225,0.604,985.0,364.0,2.060,0.915,8005.0,2968.0,2.318,0.733,11917.0,4849.0,2.190,0.647,8355.0,2910.0,2.377,0.804,10387.0,3316.0,2.545,0.686
2,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,990.263,993.166,-0.012741,NaN,2021.21,1915.00,8437.0,4046.0,2.070,0.511,17648.0,6906.0,2.353,0.634,11234.0,5299.0,2.025,0.560,9501.0,4056.0,2.226,0.555,1442.0,270.0,3.491,0.550,2104.0,402.0,3.348,1.004,9992.0,3537.0,2.559,0.639,10717.0,4551.0,2.174,0.534,11180.0,3707.0,2.623,0.696,8459.0,2720.0,2.650,0.599,8375.0,3803.0,2.086,0.515,13062.0,5910.0,2.063,0.612,22255.0,8152.0,2.465,0.664,11312.0,5432.0,1.980,0.538,9904.0,4144.0,2.301,0.578,1388.0,379.0,2.755,0.592,5155.0,2106.0,2.279,0.529,1879.0,382.0,3.122,1.072,9044.0,3162.0,2.550,0.651,14163.0,5946.0,2.202,0.570,10985.0,3501.0,2.756,0.626,11156.0,3598.0,2.670,0.631
3,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,994.619,997.755,0.075741,NaN,1893.02,2147.15,9306.0,4032.0,2.151,0.736,17246.0,5942.0,2.607,0.587,11290.0,5165.0,2.068,0.567,9668.0,3711.0,2.422,0.606,1999.0,434.0,3.530,0.726,1908.0,442.0,2.897,0.949,11585.0,3952.0,2.430,0.754,16386.0,6463.0,2.356,0.616,10877.0,3529.0,2.667,0.702,10035.0,2832.0,2.883,0.693,9806.0,4226.0,2.152,0.646,12160.0,5189.0,2.199,0.571,19469.0,6858.0,2.499,0.637,10994.0,5086.0,2.011,0.533,9418.0,3538.0,2.429,0.623,1313.0,323.0,2.785,0.897,5626.0,2166.0,2.380,0.654,2525.0,448.0,3.986,0.740,13203.0,4388.0,2.626,0.690,14826.0,5886.0,2.306,0.604,9870.0,3102.0,2.761,0.675,11579.0,3387.0,2.911,0.660
4,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,992.499,995.983,NaN,NaN,NaN,NaN,8562.0,3563.0,2.222,0.669,19502.0,6259.0,2.710,0.697,11501.0,4784.0,2.132,0.653,11182.0,3960.0,2.460,0.744,1766.0,342.0,3.198,0.840,1085.0,342.0,2.361,0.908,9580.0,3174.0,2.547,0.775,12665.0,4820.0,2.352,0.652,9296.0,3044.0,2.610,0.737,8161.0,2488.0,2.720,0.683,7701.0,3245.0,2.152,0.719,10286.0,3999.0,2.287,0.636,19993.0,6458.0,2.699,0.724,11333.0,4746.0,2.159,0.628,10519.0,3864.0,2.437,0.654,2030.0,406.0,3.418,0.625,4760.0,1762.0,2.560,0.546,1192.0,292.0,2.601,0.799,8383.0,3042.0,2.398,0.769,12710.0,4734.0,2.419,0.664,6909.0,2058.0,2.768,0.732,9641.0,2781.0,2.900,0.727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2548,7029,1178.30,927.857,250.440,513.704,413.260,2.778,2.586,5.364,307.882,625.971,453.910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2549,7030,1067.44,848.695,218.747,486.115,362.580,3.191,3.237,6.428,289.778,590.494,405.470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2550,7033,1075.41,818.695,256.720,459.958,355.181,2.562,2.349,4.911,320.702,565.862,400.240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2551,7044,1177.35,823.368,353.986,495.517,325.329,2.528,2.145,4.673,418.978,598.189,352.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2552,7048,1171.14,901.091,270.049,531.572,369.470,2.975,3.074,6.049,356.803,631.309,414.506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [96]:
def visit(visit_str):
    if visit_str == 'bl': #baseline
        return 0
    elif visit_str == 'sc': #screen (normalmente 1 mes antes del baseline)
        return 0
    elif visit_str == 'f': #fail
        return -1
    else:
        try:
            visit_num = visit_str.replace('m', '')
            visit_num = float(visit_num)
            return visit_num
        except:
            return None

In [97]:
temp = pd.read_csv('../archivos_originales/mri/ADNI_UCD_WMH_05_02_22.csv')
df = temp[['RID', 'VISCODE2', 'CEREBRUM_TCV', 'CEREBRUM_TCB', 'CEREBRUM_TCC', 'CEREBRUM_GRAY', 'CEREBRUM_WHITE', 'LEFT_HIPPO',
'RIGHT_HIPPO', 'TOTAL_HIPPO', 'TOTAL_CSF', 'TOTAL_GRAY', 'TOTAL_WHITE']].copy()
df.rename(columns={'CEREBRUM_TCV': 'CEREB_TCV', 'CEREBRUM_TCB': 'CEREB_TCB', 'CEREBRUM_TCC': 'CEREB_TCC', 'CEREBRUM_GRAY': 'CEREB_GRAY',
'CEREBRUM_WHITE': 'CEREB_WHITE', 'LEFT_HIPPO': 'L_HIPPO', 'RIGHT_HIPPO': 'R_HIPPO'}, inplace=True)
df['VISCODE2'] = df['VISCODE2'].astype('str')
df['Visit'] = df['VISCODE2'].apply(visit)
df.drop(columns=['VISCODE2'], inplace=True)

In [98]:
temp = pd.read_csv('../archivos_originales/mri/TBM_03_17_2022.csv')
df2 = temp[['RID', 'VISCODE', 'MEASURE_1', 'MEASURE_2']].copy()
df2.rename(columns={'MEASURE_1': 'TBM_1', 'MEASURE_2': 'TBM_2'}, inplace=True)
df2['VISCODE'] = df2['VISCODE'].astype('str')
df2['Visit'] = df2['VISCODE'].apply(visit)
df2.drop(columns=['VISCODE'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [99]:
temp = pd.read_csv('../archivos_originales/mri/BAIMRINMRC_09_12_16.csv')
df2 = temp[['RID', 'VISCODE2', 'IPCA']].copy()
df2 = df2[df2['IPCA'].notna()]
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [100]:
temp = pd.read_csv('../archivos_originales/mri/UCSFSNTVOL.csv')
df2 = temp[['RID', 'VISCODE', 'LEFTHIPPO', 'RIGHTHIPPO']].copy()
df2.rename(columns={'LEFTHIPPO': 'LHIPPO', 'RIGHTHIPPO': 'RHIPPO'}, inplace=True)
df2['VISCODE'] = df2['VISCODE'].astype('str')
df2['Visit'] = df2['VISCODE'].apply(visit)
df2.drop(columns=['VISCODE'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [4]:
temp = pd.read_csv('../archivos_originales/mri/UCSFFSX51_11_08_19.csv')
temp = temp[['RID', 'VISCODE2', 'ST103CV', 'ST103SA', 'ST103TA', 'ST103TS', 'ST111CV', 'ST111SA', 'ST111TA', 'ST111TS', 'ST115CV', 'ST115SA', 'ST115TA', 'ST115TS', 'ST116CV', 'ST116SA',
'ST116TA', 'ST116TS', 'ST118CV', 'ST118SA', 'ST118TA', 'ST118TS', 'ST119CV', 'ST119SA', 'ST119TA', 'ST119TS', 'ST12SV', 'ST24CV', 'ST24SA', 'ST24TA',
'ST24TS', 'ST26CV', 'ST26SA', 'ST26TA', 'ST26TS', 'ST29SV', 'ST31CV', 'ST31SA', 'ST31TA', 'ST31TS', 'ST32CV', 'ST32SA', 'ST32TA', 'ST32TS', 'ST35CV', 'ST35SA', 'ST35TA', 'ST35TS', 'ST40CV',
'ST40SA', 'ST40TA', 'ST40TS', 'ST44CV', 'ST44SA', 'ST44TA', 'ST44TS', 'ST52CV', 'ST52SA', 'ST52TA', 'ST52TS', 'ST55CV', 'ST55SA', 'ST55TA', 'ST55TS', 'ST56CV', 'ST56SA', 'ST56TA',
'ST56TS', 'ST57CV', 'ST57SA', 'ST57TA', 'ST57TS', 'ST59CV', 'ST59SA', 'ST59TA', 'ST59TS', 'ST60CV', 'ST60SA', 'ST60TA', 'ST60TS', 'ST71SV', 'ST74CV',
'ST74SA', 'ST74TA', 'ST74TS', 'ST83CV', 'ST83SA', 'ST83TA', 'ST83TS', 'ST85CV', 'ST85SA', 'ST85TA', 'ST85TS', 'ST88_SV', 'ST90CV', 'ST90SA', 'ST90TA', 'ST90TS', 'ST91CV', 'ST91SA', 'ST91TA', 'ST91TS', 'ST94CV', 'ST94SA', 'ST94TA', 'ST94TS', 'ST99CV', 'ST99SA', 'ST99TA', 'ST99TS']].copy()
temp.rename(columns={'VISCODE2': 'VISCODE'}, inplace=True)
temp2 = pd.read_csv('../archivos_originales/mri/UCSFFSX_11_02_15.csv')
temp2 = temp2[['RID', 'VISCODE', 'ST103CV', 'ST103SA', 'ST103TA', 'ST103TS', 'ST111CV', 'ST111SA', 'ST111TA', 'ST111TS', 'ST115CV', 'ST115SA', 'ST115TA', 'ST115TS', 'ST116CV', 'ST116SA',
'ST116TA', 'ST116TS', 'ST118CV', 'ST118SA', 'ST118TA', 'ST118TS', 'ST119CV', 'ST119SA', 'ST119TA', 'ST119TS', 'ST12SV', 'ST24CV', 'ST24SA', 'ST24TA',
'ST24TS', 'ST26CV', 'ST26SA', 'ST26TA', 'ST26TS', 'ST29SV', 'ST31CV', 'ST31SA', 'ST31TA', 'ST31TS', 'ST32CV', 'ST32SA', 'ST32TA', 'ST32TS', 'ST35CV', 'ST35SA', 'ST35TA', 'ST35TS', 'ST40CV', 'ST40SA', 'ST40TA', 'ST40TS',
'ST44CV', 'ST44SA', 'ST44TA', 'ST44TS', 'ST52CV', 'ST52SA', 'ST52TA', 'ST52TS', 'ST55CV', 'ST55SA', 'ST55TA', 'ST55TS', 'ST56CV', 'ST56SA', 'ST56TA',
'ST56TS', 'ST57CV', 'ST57SA', 'ST57TA', 'ST57TS', 'ST59CV', 'ST59SA', 'ST59TA', 'ST59TS', 'ST60CV', 'ST60SA', 'ST60TA', 'ST60TS', 'ST71SV', 'ST74CV',
'ST74SA', 'ST74TA', 'ST74TS', 'ST83CV', 'ST83SA', 'ST83TA', 'ST83TS', 'ST85CV', 'ST85SA', 'ST85TA', 'ST85TS', 'ST88_SV', 'ST90CV', 'ST90SA', 'ST90TA', 'ST90TS',
'ST91CV', 'ST91SA', 'ST91TA', 'ST91TS', 'ST94CV', 'ST94SA', 'ST94TA', 'ST94TS', 'ST99CV', 'ST99SA', 'ST99TA', 'ST99TS']].copy()
temp = pd.merge(temp, temp2, on=['RID', 'VISCODE', 'ST103CV', 'ST103SA', 'ST103TA', 'ST103TS', 'ST111CV', 'ST111SA', 'ST111TA', 'ST111TS', 'ST115CV', 'ST115SA', 'ST115TA', 'ST115TS',
'ST116CV', 'ST116SA', 'ST116TA', 'ST116TS', 'ST118CV', 'ST118SA', 'ST118TA', 'ST118TS', 'ST119CV', 'ST119SA', 'ST119TA', 'ST119TS', 'ST12SV', 'ST24CV',
'ST24SA', 'ST24TA', 'ST24TS', 'ST26CV', 'ST26SA', 'ST26TA', 'ST26TS', 'ST29SV', 'ST31CV', 'ST31SA', 'ST31TA', 'ST31TS', 'ST32CV', 'ST32SA', 'ST32TA',
'ST32TS', 'ST35CV', 'ST35SA', 'ST35TA', 'ST35TS', 'ST40CV', 'ST40SA', 'ST40TA', 'ST40TS', 'ST44CV', 'ST44SA', 'ST44TA', 'ST44TS', 'ST52CV', 'ST52SA', 'ST52TA', 'ST52TS', 'ST55CV', 'ST55SA', 'ST55TA', 'ST55TS', 'ST56CV',
'ST56SA', 'ST56TA', 'ST56TS', 'ST57CV', 'ST57SA', 'ST57TA', 'ST57TS', 'ST59CV', 'ST59SA', 'ST59TA', 'ST59TS', 'ST60CV', 'ST60SA', 'ST60TA',
'ST60TS', 'ST71SV', 'ST74CV', 'ST74SA', 'ST74TA', 'ST74TS', 'ST83CV', 'ST83SA', 'ST83TA', 'ST83TS', 'ST85CV', 'ST85SA', 'ST85TA', 'ST85TS', 'ST88_SV', 'ST90CV', 'ST90SA', 'ST90TA', 'ST90TS',
'ST91CV', 'ST91SA', 'ST91TA', 'ST91TS', 'ST94CV', 'ST94SA', 'ST94TA', 'ST94TS', 'ST99CV', 'ST99SA', 'ST99TA', 'ST99TS'], how='outer')

temp['VISCODE'] = temp['VISCODE'].astype('str')
temp['Visit'] = temp['VISCODE'].apply(visit)
temp.drop(columns=['VISCODE'], inplace=True)

df = pd.merge(df, temp, on=['RID', 'Visit'], how='outer')

array(['Pass', 'Fail', nan], dtype=object)

In [102]:
df = df[['RID', 'Visit', 'CEREB_TCV', 'CEREB_TCB', 'CEREB_TCC', 'CEREB_GRAY', 'CEREB_WHITE', 'L_HIPPO', 'R_HIPPO', 'TOTAL_HIPPO', 'TOTAL_CSF',
'TOTAL_GRAY', 'TOTAL_WHITE', 'TBM_1', 'TBM_2', 'IPCA', 'LHIPPO', 'RHIPPO', 'ST103CV', 'ST103SA', 'ST103TA', 'ST103TS', 'ST111CV', 'ST111SA', 'ST111TA', 'ST111TS', 'ST115CV', 'ST115SA',
'ST115TA', 'ST115TS', 'ST116CV', 'ST116SA', 'ST116TA', 'ST116TS', 'ST118CV', 'ST118SA', 'ST118TA', 'ST118TS', 'ST119CV', 'ST119SA', 'ST119TA',
'ST119TS', 'ST12SV', 'ST24CV', 'ST24SA', 'ST24TA', 'ST24TS', 'ST26CV', 'ST26SA', 'ST26TA', 'ST26TS', 'ST29SV', 'ST31CV', 'ST31SA', 'ST31TA', 'ST31TS', 'ST32CV',
'ST32SA', 'ST32TA', 'ST32TS', 'ST35CV', 'ST35SA', 'ST35TA', 'ST35TS', 'ST40CV', 'ST40SA', 'ST40TA', 'ST40TS', 'ST44CV', 'ST44SA', 'ST44TA', 'ST44TS', 'ST52CV', 'ST52SA', 'ST52TA', 'ST52TS', 'ST55CV', 'ST55SA', 'ST55TA',
'ST55TS', 'ST56CV', 'ST56SA', 'ST56TA', 'ST56TS', 'ST57CV', 'ST57SA', 'ST57TA', 'ST57TS', 'ST59CV', 'ST59SA', 'ST59TA', 'ST59TS', 'ST60CV',
'ST60SA', 'ST60TA', 'ST60TS', 'ST71SV', 'ST74CV', 'ST74SA', 'ST74TA', 'ST74TS', 'ST83CV', 'ST83SA', 'ST83TA', 'ST83TS', 'ST85CV', 'ST85SA', 'ST85TA',
'ST85TS', 'ST88_SV', 'ST90CV', 'ST90SA', 'ST90TA', 'ST90TS', 'ST91CV', 'ST91SA', 'ST91TA', 'ST91TS', 'ST94CV', 'ST94SA', 'ST94TA', 'ST94TS', 'ST99CV', 'ST99SA', 'ST99TA', 'ST99TS']]
df = df.sort_values('RID')
df

,RID,Visit,CEREB_TCV,CEREB_TCB,CEREB_TCC,CEREB_GRAY,CEREB_WHITE,L_HIPPO,R_HIPPO,TOTAL_HIPPO,TOTAL_CSF,TOTAL_GRAY,TOTAL_WHITE,TBM_1,TBM_2,IPCA,LHIPPO,RHIPPO,ST111CV,ST111SA,ST111TA,ST111TS,ST115CV,ST115SA,ST115TA,ST115TS,ST116CV,ST116SA,ST116TA,ST116TS,ST118CV,ST118SA,ST118TA,ST118TS,ST119CV,ST119SA,ST119TA,ST119TS,ST24CV,ST24SA,ST24TA,ST24TS,ST26CV,ST26SA,ST26TA,ST26TS,ST31CV,ST31SA,ST31TA,ST31TS,ST32CV,ST32SA,ST32TA,ST32TS,ST40CV,ST40SA,ST40TA,ST40TS,ST52CV,ST52SA,ST52TA,ST52TS,ST55CV,ST55SA,ST55TA,ST55TS,ST56CV,ST56SA,ST56TA,ST56TS,ST57CV,ST57SA,ST57TA,ST57TS,ST59CV,ST59SA,ST59TA,ST59TS,ST60CV,ST60SA,ST60TA,ST60TS,ST74CV,ST74SA,ST74TA,ST74TS,ST83CV,ST83SA,ST83TA,ST83TS,ST85CV,ST85SA,ST85TA,ST85TS,ST90CV,ST90SA,ST90TA,ST90TS,ST91CV,ST91SA,ST91TA,ST91TS,ST99CV,ST99SA,ST99TA,ST99TS
14063,2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8856.0,3886.0,2.211,0.658,23577.0,8209.0,2.691,0.720,13054.0,6010.0,2.017,0.650,8892.0,3521.0,2.279,0.787,1765.0,297.0,3.904,0.658,2241.0,507.0,3.254,1.022,9307.0,3116.0,2.561,0.784,12035.0,4802.0,2.301,0.557,12098.0,3669.0,2.779,0.727,12253.0,3587.0,2.795,0.740,8319.0,3795.0,2.166,0.579,18039.0,7100.0,2.318,0.644,23583.0,7984.0,2.655,0.697,13753.0,6196.0,2.077,0.648,9924.0,3866.0,2.446,0.551,1635.0,355.0,3.236,0.684,6566.0,2600.0,2.363,0.736,1936.0,320.0,3.610,0.925,7252.0,2418.0,2.727,0.724,15789.0,6612.0,2.243,0.650,11155.0,3273.0,2.901,0.688,15683.0,4272.0,3.028,0.649
13229,3,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.317268,1698.17,1419.86,8112.0,3721.0,2.052,0.561,20473.0,7458.0,2.426,0.721,10405.0,4807.0,1.920,0.597,9424.0,3717.0,2.289,0.657,1341.0,309.0,2.964,0.677,806.0,370.0,1.805,0.815,7501.0,2911.0,2.234,0.727,8558.0,3657.0,2.102,0.567,9008.0,3226.0,2.348,0.683,8035.0,2698.0,2.453,0.685,7922.0,3560.0,2.051,0.591,15602.0,6725.0,2.026,0.646,21166.0,7397.0,2.494,0.696,11181.0,4988.0,2.033,0.601,9988.0,3819.0,2.321,0.563,1813.0,355.0,3.574,0.786,4833.0,1948.0,2.225,0.604,985.0,364.0,2.060,0.915,8005.0,2968.0,2.318,0.733,11917.0,4849.0,2.190,0.647,8355.0,2910.0,2.377,0.804,10387.0,3316.0,2.545,0.686
10346,3,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,978.439,992.628,NaN,1741.19,1489.52,8089.0,3725.0,2.065,0.594,19446.0,7096.0,2.409,0.695,10342.0,4658.0,1.980,0.621,9266.0,3739.0,2.259,0.669,1159.0,368.0,2.450,0.714,1244.0,461.0,2.103,1.045,7390.0,2851.0,2.209,0.794,8095.0,3619.0,2.015,0.569,8746.0,3214.0,2.312,0.663,7661.0,2713.0,2.373,0.695,7444.0,3465.0,1.992,0.589,15072.0,6529.0,2.012,0.653,21359.0,7419.0,2.483,0.696,10842.0,5051.0,1.945,0.600,9729.0,3815.0,2.271,0.573,1547.0,325.0,3.464,0.804,5139.0,1975.0,2.308,0.575,1183.0,470.0,2.077,0.909,7010.0,2730.0,2.240,0.673,11950.0,4811.0,2.207,0.631,8612.0,3015.0,2.398,0.781,9311.0,3138.0,2.445,0.713
10347,3,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,966.409,989.194,NaN,1482.95,1229.62,7580.0,3733.0,1.972,0.570,19288.0,7184.0,2.409,0.727,9988.0,4701.0,1.889,0.613,9194.0,3754.0,2.232,0.650,1350.0,329.0,2.887,0.690,762.0,343.0,1.770,0.679,6993.0,2919.0,2.090,0.692,7660.0,3673.0,1.918,0.568,8611.0,3205.0,2.334,0.651,7594.0,2607.0,2.445,0.682,7259.0,3662.0,1.887,0.542,13798.0,6331.0,1.956,0.639,20229.0,7414.0,2.446,0.655,10613.0,5074.0,1.916,0.625,9138.0,3843.0,2.154,0.624,1536.0,326.0,3.327,0.805,5245.0,2105.0,2.244,0.607,834.0,349.0,1.961,0.887,7624.0,2923.0,2.228,0.675,11785.0,4754.0,2.187,0.634,7542.0,2811.0,2.281,0.729,9736.0,3240.0,2.502,0.685
10348,3,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,926.894,973.900,NaN,NaN,NaN,7697.0,3648.0,2.018,0.577,20279.0,7196.0,2.478,0.727,9957.0,4646.0,1.902,0.605,9073.0,3713.0,2.212,0.670,1279.0,325.0,2.741,0.720,630.0,354.0,1.506,0.610,6769.0,2833.0,2.055,0.719,7718.0,3569.0,1.967,0.555,8098.0,3101.0,2.245,0.641,7082.0,2586.0,2.332,0.641,7213.0,3457.0,1.922,0.574,15137.0,6562.0,2.019,0.644,20700.0,7194.0,2.505,0.671,10744.0,4890.0,1.976,0.635,9452.0,3759.0,2.246,0.598,1521.0,370.0,2.986,0.910,5053.0,2005.0,2.244,0.650,545.0,307.0,1.434,0.891,7264.0,2845.0,2.218,0.673,11152.0,4507.0,2.172,0.665,7534.0,2730.0,2.325,0.800,9316.0,3097.0,2.474,0.677
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10341,7029,0.0,1178.30,927.857,250.440,513.704,413.260,2.778,2.586,5.364,307.882,625.971,453.910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10342,7030,0.0,1067.44,848.695,218.747,486.115,362.580,3.191,3.237,6.428,289.778,590.494,405.470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10343,7033,0.0,1075.41,818.695,256.720,459.958,355.181,2.562,2.349,4.911,320.702,565.862,400.240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10344,7044,0.0,1177.35,823.368,353.986,495.517,325.329,2.528,2.145,4.673,418.978,598.189,352.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10345,7048,0.0,1171.14,901.091,270.049,531.572,369.470,2.975,3.074,6.049,356.803,631.309,414.506,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.to_csv('mri.csv', index=False)