In [1]:
import pickle
import ast
import pandas as pd
from collections import Counter

In [2]:
def load_pickle(file):
    """
    load a pickle file into a local variable
    can be a pandas dataframe or dictionary
    """
    pickle_in = open(file, "rb")
    pickle_file = pickle.load(pickle_in)
    pickle_in.close()
    return pickle_file

In [ ]:
node_dict = load_pickle('../node_dictionary.pickle')
top_paths = load_pickle('paper/results_pearson/network_paths/top_pathways.pickle')

# Negative Controls

In [ ]:
n_permutations = 100
my_count = {}
for i in range(4):
    for n in range(n_permutations):
        d = load_pickle(f'/paper/results_pearson/negative_controls/negative_controls_net{i}/top_pathways_permuted_net{i}_{n}.pickle')
        for val in d.values():
            for el in val.values():
                for l in el:
                    if str(l) in my_count:
                        my_count[str(l)] += 1
                    else:
                        my_count[str(l)] = 1

Hay un problema con el dict que guarda los top paths: las keys son strings, no listas. Tengo que transformarlo.

In [47]:
rows = []
for key, el in my_count.items():
    key = ast.literal_eval(key)
    rows.append({"path": key, "count": el})

df = pd.DataFrame(rows)

In [48]:
df

                                                      path  count
0                                      [APOE_A1, TL, MMSE]     79
1                                          [APOE_A1, MMSE]    217
2                                 [APOE_A1, HMONSET, MMSE]     76
3                                  [APOE_A1, PTHAND, MMSE]    103
4                           [APOE_A1, TMPINFR01_FDG, MMSE]      6
...                                                    ...    ...
2190267              [MH17MALI, HMSTROKE, AXSWEATN, UW_EF]      1
2190268               [MH17MALI, HMSTROKE, APOE_A1, UW_EF]      1
2190269             [MH17MALI, HMSTROKE, CEREB_TCC, UW_EF]      1
2190270  [MH17MALI, HMSTROKE, RH_ROSTRALANTERIORCINGULA...      1
2190271              [MH17MALI, HMSTROKE, AXPALPIT, UW_EF]      1

[2190272 rows x 2 columns]

In [49]:
paths = []
for _, value in top_paths.items():
    for _, elements in value.items():
        for el in elements:
            paths.append(el)
paths_permuted = df.path.tolist()

In [50]:
print(len(paths))
print(len(paths_permuted))

27840
2190272

In [51]:
not_in_permuted = [x for x in paths if x not in paths_permuted]
len(not_in_permuted)

17877

In [52]:
rows = []
for el in not_in_permuted:
    rows.append({"path": el, "count": 0})
df_append = pd.DataFrame(rows)
df_append

                                             path  count
0                   [APOE_A1, ANGULL02_FDG, MMSE]      0
1                        [APOE_A1, HMSCORE, MMSE]      0
2              [APOE_A1, ANGULL01_FDG, APP, MMSE]      0
3           [APOE_A1, ANGULL01_FDG, AXRASH, MMSE]      0
4         [APOE_A1, ANGULL01_FDG, AXDROWSY, MMSE]      0
...                                           ...    ...
17872   [MH18SURG, CINGPST07_FDG, AXDIZZY, UW_EF]      0
17873  [MH18SURG, CINGPST07_FDG, AXSWEATN, UW_EF]      0
17874  [MH18SURG, CINGPST07_FDG, AXWANDER, UW_EF]      0
17875   [MH18SURG, CINGPST07_FDG, MH7DERM, UW_EF]      0
17876   [MH18SURG, CINGPST07_FDG, AXVOMIT, UW_EF]      0

[17877 rows x 2 columns]

In [53]:
# concatenate the dataframes vertically
df = pd.concat([df, df_append], ignore_index=True)
df

                                               path  count
0                               [APOE_A1, TL, MMSE]     79
1                                   [APOE_A1, MMSE]    217
2                          [APOE_A1, HMONSET, MMSE]     76
3                           [APOE_A1, PTHAND, MMSE]    103
4                    [APOE_A1, TMPINFR01_FDG, MMSE]      6
...                                             ...    ...
2208144   [MH18SURG, CINGPST07_FDG, AXDIZZY, UW_EF]      0
2208145  [MH18SURG, CINGPST07_FDG, AXSWEATN, UW_EF]      0
2208146  [MH18SURG, CINGPST07_FDG, AXWANDER, UW_EF]      0
2208147   [MH18SURG, CINGPST07_FDG, MH7DERM, UW_EF]      0
2208148   [MH18SURG, CINGPST07_FDG, AXVOMIT, UW_EF]      0

[2208149 rows x 2 columns]

In [54]:
df[df['count'] == 0]

                                               path  count
2190272               [APOE_A1, ANGULL02_FDG, MMSE]      0
2190273                    [APOE_A1, HMSCORE, MMSE]      0
2190274          [APOE_A1, ANGULL01_FDG, APP, MMSE]      0
2190275       [APOE_A1, ANGULL01_FDG, AXRASH, MMSE]      0
2190276     [APOE_A1, ANGULL01_FDG, AXDROWSY, MMSE]      0
...                                             ...    ...
2208144   [MH18SURG, CINGPST07_FDG, AXDIZZY, UW_EF]      0
2208145  [MH18SURG, CINGPST07_FDG, AXSWEATN, UW_EF]      0
2208146  [MH18SURG, CINGPST07_FDG, AXWANDER, UW_EF]      0
2208147   [MH18SURG, CINGPST07_FDG, MH7DERM, UW_EF]      0
2208148   [MH18SURG, CINGPST07_FDG, AXVOMIT, UW_EF]      0

[17877 rows x 2 columns]

In [55]:
df[df['count'] <= 1]

                                                   path  count
139              [APOE_A2, PTHAND, TMPINFL11_FDG, MOCA]      1
149                     [APOE_A2, PTHAND, ST111CV, CDR]      1
156                     [APOE_A2, PTHAND, CDR, ADSP_DX]      1
157      [APOE_A2, PTHAND, LH_ENTORHINAL_AV45, ADSP_DX]      1
169          [APOE_A2, PTHAND, TMPINFL11_FDG, ADSP_MEM]      1
...                                                 ...    ...
2208144       [MH18SURG, CINGPST07_FDG, AXDIZZY, UW_EF]      0
2208145      [MH18SURG, CINGPST07_FDG, AXSWEATN, UW_EF]      0
2208146      [MH18SURG, CINGPST07_FDG, AXWANDER, UW_EF]      0
2208147       [MH18SURG, CINGPST07_FDG, MH7DERM, UW_EF]      0
2208148       [MH18SURG, CINGPST07_FDG, AXVOMIT, UW_EF]      0

[1481733 rows x 2 columns]

In [56]:
path_pass = df[df['count'] == 0].path.tolist() # pathways that are present in less than 1% of the permuted pathways

In [57]:
rows = []
for el in path_pass:
    rows.append({"path": el, "source": el[0], "target": el[-1]})
df_pass = pd.DataFrame(rows)
df_pass

                                             path    source target
0                   [APOE_A1, ANGULL02_FDG, MMSE]   APOE_A1   MMSE
1                        [APOE_A1, HMSCORE, MMSE]   APOE_A1   MMSE
2              [APOE_A1, ANGULL01_FDG, APP, MMSE]   APOE_A1   MMSE
3           [APOE_A1, ANGULL01_FDG, AXRASH, MMSE]   APOE_A1   MMSE
4         [APOE_A1, ANGULL01_FDG, AXDROWSY, MMSE]   APOE_A1   MMSE
...                                           ...       ...    ...
17872   [MH18SURG, CINGPST07_FDG, AXDIZZY, UW_EF]  MH18SURG  UW_EF
17873  [MH18SURG, CINGPST07_FDG, AXSWEATN, UW_EF]  MH18SURG  UW_EF
17874  [MH18SURG, CINGPST07_FDG, AXWANDER, UW_EF]  MH18SURG  UW_EF
17875   [MH18SURG, CINGPST07_FDG, MH7DERM, UW_EF]  MH18SURG  UW_EF
17876   [MH18SURG, CINGPST07_FDG, AXVOMIT, UW_EF]  MH18SURG  UW_EF

[17877 rows x 3 columns]

In [58]:
df_pass.to_csv('pass_paths.csv', index=False) # paths que han pasado los negative controls

Paths identified when the input started at
- the genetics
- the molecular
- the PET
- the MRI
- the risk factors

In [59]:
df_pass

                                             path    source target
0                   [APOE_A1, ANGULL02_FDG, MMSE]   APOE_A1   MMSE
1                        [APOE_A1, HMSCORE, MMSE]   APOE_A1   MMSE
2              [APOE_A1, ANGULL01_FDG, APP, MMSE]   APOE_A1   MMSE
3           [APOE_A1, ANGULL01_FDG, AXRASH, MMSE]   APOE_A1   MMSE
4         [APOE_A1, ANGULL01_FDG, AXDROWSY, MMSE]   APOE_A1   MMSE
...                                           ...       ...    ...
17872   [MH18SURG, CINGPST07_FDG, AXDIZZY, UW_EF]  MH18SURG  UW_EF
17873  [MH18SURG, CINGPST07_FDG, AXSWEATN, UW_EF]  MH18SURG  UW_EF
17874  [MH18SURG, CINGPST07_FDG, AXWANDER, UW_EF]  MH18SURG  UW_EF
17875   [MH18SURG, CINGPST07_FDG, MH7DERM, UW_EF]  MH18SURG  UW_EF
17876   [MH18SURG, CINGPST07_FDG, AXVOMIT, UW_EF]  MH18SURG  UW_EF

[17877 rows x 3 columns]

In [61]:
for layer in node_dict.keys():
    df_temp = df_pass[df_pass.source.isin(node_dict[layer].copy())]
    print(f'Total number of paths when the input started in the {layer} layer: {len(df_temp)}')

    #Number of times nodes appear in the paths
    counters = [Counter(lst) for lst in df_temp.path.tolist()] # Create a Counter object for each list
    my_dict = dict(sum(counters, Counter())) # Merge the Counter objects into one dictionary

    for key, values in node_dict.items():
        print('-------', key, '--------------')
        for node, count in my_dict.items():
            if node in values:
                print(node, count)
    print('')

Total number of paths when the input started in the GENETIC layer: 297
------- GENETIC --------------
APOE_A1 52
APOE_A2 37
APOE 35
TOMM40_A1 40
TOMM40_A2 47
PHS 29
CIR 58
------- MOLECULAR --------------
APP 9
UPKelec_AB42 3
------- PET --------------
ANGULL02_FDG 9
ANGULL01_FDG 33
ANGULR02_FDG 8
TMPINFR06_FDG 4
ANGULR01_FDG 1
CINGPSTL02_FDG 1
CINGPST03_FDG 31
ANGULR04_FDG 5
CINGPSTL01_FDG 5
------- MRI --------------
------- RISKFACTORS --------------
HMSCORE 70
AXRASH 10
AXDROWSY 8
AXCONSTP 1
AXNAUSEA 1
AXDIARRH 62
AXENERGY 40
MH4CARD 1
AXDPMOOD 18
AXCRYING 15
AXVOMIT 4
AXWANDER 2
MH18SURG 1
AXPALPIT 8
MH13ALLE 1
MH3HEAD 1
AXANKLE 1
MH10GAST 1
AXDRYMTH 1
------- PHENOTYPE --------------
MMSE 29
MOCA 32
UW_MEM 33
CDR 18
ADSP_DX 13
ADSP_MEM 31
ADSP_EXF 37
ADSP_LAN 31
ADSP_VSP 25
ADAS11 14
ADAS13 13
UW_EF 32

Total number of paths when the input started in the MOLECULAR layer: 1242
------- GENETIC --------------
TOMM40_A2 7
APOE_A1 16
CIR 8
APOE_A2 2
------- MOLECULAR --------------
EUR_AB42 96
EUR_AB42/40 59
FUJI_AB42 69
FUJI_AB42/40 85
UPplasma_AB42 59
APP 154
UPKelec_AB42 104
UGOT_PLASMAPTAU 38
TS_RATIO 60
TL 85
TS_RATIO_ADJ 99
BACE 88
UPK_AB42 91
UPK_TAU 79
UPK_PTAU 87
UPKelec_TAU 108
UPKelec_PTAU 100
------- PET --------------
TEMPORAL_AV45 1
LH_MIDDLETEMPORAL_AV45 2
RH_LATERALORBITOFRONTAL_AV45 14
RH_CAUDALANTERIORCINGULATE_AV45 3
RH_LATERALOCCIPITAL_AV45 5
RH_PARSTRIANGULARIS_AV45 6
RH_POSTCENTRAL_AV45 7
RH_PARSOPERCULARIS_AV45 4
HCI_FDG 4
RH_CAUDALMIDDLEFRONTAL_AV45 1
RH_INFERIORPARIETAL_AV45 2
WHOLECEREBELLUM_AV45 1
COMPOSITE_AV45 3
CINGPST04_FDG 84
ANGULR01_FDG 6
ANGULR04_FDG 13
ANGULR02_FDG 7
CINGPSTL01_FDG 18
RH_PARAHIPPOCAMPAL_AV45 10
LH_PARACENTRAL_AV45 7
LH_POSTERIORCINGULATE_AV45 5
LH_ISTHMUSCINGULATE_AV45 8
BRAAK56_SUVR 5
RH_PRECENTRAL_AV45 1
ANGULL01_FDG 213
LH_TRANSVERSETEMPORAL_AV45 8
TMPINFR05_FDG 4
SUMMARYSUVR_WHOLECEREBNORM_AV45 2
BRAAK34_SUVR 5
PARIETAL_AV45 2
RH_SUPERIORTEMPORAL_AV45 1
ANGULL02_FDG 207
TMPINFR04_FDG 9
TMPINFL04_FDG 21
RH_SUPERIORPARIETAL_AV45 1
TMPINFR06_FDG 21
CINGPST03_FDG 100
TMPINFL10_FDG 4
CINGPSTL02_FDG 86
HCI_2014_FDG 7
RH_TEMPORALPOLE_AV45 5
LH_POSTCENTRAL_AV45 1
LH_SUPERIORPARIETAL_AV45 1
RH_SUPERIORFRONTAL_AV45 3
LH_CAUDALANTERIORCINGULATE_AV45 1
------- MRI --------------
ST24CV 5
ST94CV 11
ST57CV 3
ST32CV 7
ST52CV 4
ST90CV 9
CEREB_WHITE 1
CEREB_TCC 20
CEREB_GRAY 11
ST56CV 7
ST85CV 12
ST91CV 6
RHIPPO 6
ST118CV 5
ST26CV 8
ST115CV 2
L_HIPPO 1
ST35CV 3
ST111CV 1
ST31CV 5
R_HIPPO 5
ST119CV 8
ST60CV 2
LHIPPO 4
ST99CV 4
ST103CV 1
ST55CV 4
ST116CV 4
ST83CV 1
CEREB_TCV 1
ST40CV 4
ST74CV 1
ST29SV 2
------- RISKFACTORS --------------
AXDPMOOD 167
AXENERGY 43
AXCRYING 40
HMSCORE 40
AXDIARRH 44
GDS 30
MHPSYCH 11
PTGENDER 28
HMEMOTIO 59
AXELMOOD 9
AXBREATH 9
AXCONSTP 17
AXNAUSEA 23
AXCHEST 3
MH11HEMA 17
AXWANDER 18
MH5RESP 22
MH18SURG 7
PTMARRY 8
AXPALPIT 10
AXURNFRQ 5
MH17MALI 14
MH13ALLE 15
AXMUSCLE 8
AXINSOMN 5
AXDROWSY 6
AXRASH 9
AXSWEATN 9
MH3HEAD 10
AXVOMIT 12
AXVISION 1
AXABDOMN 2
HMNEURSG 3
MH2NEURL 2
MH12RENA 9
AXURNDIS 7
MH10GAST 9
AXFALL 2
AXDRYMTH 3
HMSOMATC 2
AXDIZZY 8
AXHDACHE 7
MH15DRUG 6
------- PHENOTYPE --------------
MMSE 111
MOCA 137
CDR 105
ADSP_DX 100
ADSP_MEM 116
ADSP_EXF 104
ADSP_LAN 115
ADSP_VSP 112
ADAS11 116
ADAS13 109
UW_MEM 114
UW_EF 114

Total number of paths when the input started in the PET layer: 8494
------- GENETIC --------------
TOMM40_A2 34
APOE_A1 8
APOE_A2 7
PHS 10
CIR 8
------- MOLECULAR --------------
APP 31
UPplasma_AB42 26
FUJI_AB42/40 8
TL 31
TS_RATIO_ADJ 18
TS_RATIO 23
UPKelec_PTAU 32
UPKelec_TAU 32
UPK_TAU 1
EUR_AB42/40 4
UGOT_PLASMAPTAU 13
FUJI_AB42 5
UPK_AB42 10
BACE 161
UPKelec_AB42 4
EUR_AB42 9
UPK_PTAU 5
------- PET --------------
MEAN_METAROI_PONSVERMIS 69
BRAAK1_SUVR 103
ANGULL02_FDG 290
TMPINFL04_FDG 134
BRAAK34_SUVR 101
TMPINFR06_FDG 154
BRAAK56_SUVR 77
CEREBELLUMGREYMATTER_AV45 105
RH_ROSTRALMIDDLEFRONTAL_AV45 92
LH_PARAHIPPOCAMPAL_AV45 168
RH_LATERALORBITOFRONTAL_AV45 74
WHOLECEREBELLUM_AV45 105
RH_LINGUAL_AV45 104
LH_ISTHMUSCINGULATE_AV45 91
RH_PRECENTRAL_AV45 144
LH_SUPERIORPARIETAL_AV45 80
FRONTAL_AV45 97
LH_TRANSVERSETEMPORAL_AV45 82
LH_PARSTRIANGULARIS_AV45 106
CINGULATE_AV45 85
HCI_2014_FDG 84
PARIETAL_AV45 89
TEMPORAL_AV45 86
LH_PRECENTRAL_AV45 150
LH_LATERALOCCIPITAL_AV45 74
RH_PARACENTRAL_AV45 89
LH_LATERALORBITOFRONTAL_AV45 106
LH_MEDIALORBITOFRONTAL_AV45 92
COMPOSITE_AV45 85
RH_INFERIORPARIETAL_AV45 102
SUMMARYSUVR_WHOLECEREBNORM_AV45 87
SUMMARYSUVR_COMPOSITE_REFNORM_AV45 78
LH_CAUDALANTERIORCINGULATE_AV45 80
ANGULR03_FDG 70
RH_ENTORHINAL_AV45 157
LH_CAUDALMIDDLEFRONTAL_AV45 138
ANGULR04_FDG 1009
LH_CUNEUS_AV45 99
LH_PARACENTRAL_AV45 120
LH_TEMPORALPOLE_AV45 153
RH_TEMPORALPOLE_AV45 195
LH_POSTCENTRAL_AV45 161
RH_SUPERIORPARIETAL_AV45 152
LH_ENTORHINAL_AV45 97
LH_FUSIFORM_AV45 84
LH_PRECUNEUS_AV45 93
LH_FRONTALPOLE_AV45 86
LH_INFERIORPARIETAL_AV45 102
LH_PARSORBITALIS_AV45 98
LH_INFERIORTEMPORAL_AV45 82
LH_INSULA_AV45 90
RH_PARSOPERCULARIS_AV45 91
LH_SUPERIORFRONTAL_AV45 72
RH_POSTERIORCINGULATE_AV45 84
LH_LINGUAL_AV45 91
LH_MIDDLETEMPORAL_AV45 87
LH_PARSOPERCULARIS_AV45 82
RH_POSTCENTRAL_AV45 146
LH_POSTERIORCINGULATE_AV45 78
RH_MIDDLETEMPORAL_AV45 88
RH_PRECUNEUS_AV45 94
LH_ROSTRALANTERIORCINGULATE_AV45 100
LH_ROSTRALMIDDLEFRONTAL_AV45 81
RH_FRONTALPOLE_AV45 89
LH_SUPERIORTEMPORAL_AV45 86
LH_SUPRAMARGINAL_AV45 92
RH_PARSTRIANGULARIS_AV45 77
RH_SUPERIORTEMPORAL_AV45 78
RH_CAUDALANTERIORCINGULATE_AV45 98
RH_PARSORBITALIS_AV45 86
RH_CAUDALMIDDLEFRONTAL_AV45 77
RH_CUNEUS_AV45 50
TMPINFL06_FDG 78
RH_FUSIFORM_AV45 73
RH_INFERIORTEMPORAL_AV45 86
RH_INSULA_AV45 76
RH_ISTHMUSCINGULATE_AV45 77
RH_SUPERIORFRONTAL_AV45 69
RH_LATERALOCCIPITAL_AV45 80
RH_MEDIALORBITOFRONTAL_AV45 70
RH_PARAHIPPOCAMPAL_AV45 83
RH_ROSTRALANTERIORCINGULATE_AV45 99
RH_SUPRAMARGINAL_AV45 82
RH_TRANSVERSETEMPORAL_AV45 82
ANGULL01_FDG 127
ANGULR01_FDG 88
ANGULR02_FDG 182
CINGPSTL01_FDG 217
CINGPST03_FDG 180
ANGULR05_FDG 87
TMPINFR05_FDG 103
CINGPSTL02_FDG 275
CINGPST04_FDG 81
HCI_FDG 76
CINGPST05_FDG 39
CINGPST07_FDG 73
CINGPST09_FDG 46
CINGPSTR12_FDG 105
TMPINFR01_FDG 45
TMPINFL02_FDG 86
TMPINFL03_FDG 85
TMPINFR03_FDG 101
TMPINFR04_FDG 189
TMPINFL09_FDG 47
TMPINFL10_FDG 71
TMPINFL11_FDG 109
------- MRI --------------
CEREB_TCC 45
CEREB_TCV 29
CEREB_GRAY 30
ST119CV 46
ST52CV 74
ST90CV 65
RHIPPO 72
ST31CV 57
ST115CV 30
ST85CV 72
ST59CV 74
ST60CV 57
ST99CV 55
ST40CV 61
ST103CV 64
ST32CV 81
ST94CV 62
ST55CV 70
ST83CV 39
ST26CV 78
ST35CV 55
ST71SV 24
ST111CV 67
ST44CV 26
ST12SV 69
ST56CV 57
ST57CV 65
ST118CV 70
ST24CV 83
LHIPPO 44
ST74CV 57
R_HIPPO 62
L_HIPPO 31
CEREB_WHITE 46
ST88SV 36
ST91CV 88
ST29SV 40
ST116CV 48
TBM_1 5
CEREB_TCB 1
IPCA 8
------- RISKFACTORS --------------
AXDIARRH 662
AXDPMOOD 3268
HMSCORE 701
AXENERGY 553
AXCRYING 1240
PTGENDER 136
MH13ALLE 18
HMSTEPWS 17
AXHDACHE 28
AXDIZZY 38
PTMARRY 8
AXINSOMN 12
PTEDUCAT 8
PTDOBYY 7
AXDROWSY 19
MH5RESP 17
AXCONSTP 40
MH3HEAD 21
MH11HEMA 10
AXSWEATN 16
AXBREATH 30
AXRASH 6
GDS 191
MHPSYCH 87
AXCOUGH 46
AXWANDER 12
AXDRYMTH 21
AXURNDIS 26
AXELMOOD 52
MH17MALI 8
AXVOMIT 23
AXNAUSEA 28
AXMUSCLE 10
AXURNFRQ 18
AXVISION 6
AXABDOMN 11
AXANKLE 15
AXPALPIT 14
MH9ENDO 5
HMHYPERT 2
HMSOMATC 4
HMNEURSM 1
MH18SURG 18
PTHAND 15
HMNEURSG 2
MH8MUSCL 2
MH10GAST 5
AXCHEST 12
AXFALL 11
HMEMOTIO 81
MH7DERM 10
MH16SMOK 67
MH14ALCH 12
MH6HEPAT 60
------- PHENOTYPE --------------
MMSE 683
MOCA 799
CDR 764
ADSP_DX 764
ADSP_MEM 704
ADSP_EXF 711
ADSP_LAN 686
ADSP_VSP 703
ADAS11 763
ADAS13 820
UW_MEM 739
UW_EF 717

Total number of paths when the input started in the MRI layer: 3226
------- GENETIC --------------
TOMM40_A2 1
------- MOLECULAR --------------
UPplasma_AB42 3
EUR_AB42 3
FUJI_AB42 3
TS_RATIO_ADJ 8
TL 8
TS_RATIO 7
UPKelec_TAU 1
EUR_AB42/40 6
BACE 49
UGOT_PLASMAPTAU 25
------- PET --------------
CINGPST09_FDG 7
MEAN_METAROI_PONSVERMIS 2
ANGULL02_FDG 18
ANGULL01_FDG 27
ANGULR01_FDG 18
TMPINFR06_FDG 11
ANGULR02_FDG 22
ANGULR04_FDG 53
TMPINFL04_FDG 2
CINGPSTL01_FDG 27
TMPINFL10_FDG 1
LH_LATERALOCCIPITAL_AV45 3
ANGULR03_FDG 23
TEMPORAL_AV45 3
LH_FRONTALPOLE_AV45 8
LH_TEMPORALPOLE_AV45 16
LH_CUNEUS_AV45 2
RH_FRONTALPOLE_AV45 2
LH_PARSTRIANGULARIS_AV45 1
CINGPSTL02_FDG 2
HCI_2014_FDG 4
RH_INFERIORPARIETAL_AV45 5
CINGPST07_FDG 116
LH_ENTORHINAL_AV45 11
RH_TEMPORALPOLE_AV45 1
CEREBELLUMGREYMATTER_AV45 2
RH_SUPERIORPARIETAL_AV45 3
LH_LATERALORBITOFRONTAL_AV45 4
RH_LINGUAL_AV45 7
RH_CAUDALMIDDLEFRONTAL_AV45 7
RH_ENTORHINAL_AV45 1
LH_INSULA_AV45 10
RH_LATERALORBITOFRONTAL_AV45 1
LH_ROSTRALMIDDLEFRONTAL_AV45 3
LH_ISTHMUSCINGULATE_AV45 4
RH_SUPRAMARGINAL_AV45 1
RH_PARSTRIANGULARIS_AV45 4
LH_TRANSVERSETEMPORAL_AV45 2
LH_PARSORBITALIS_AV45 2
RH_CAUDALANTERIORCINGULATE_AV45 1
RH_POSTERIORCINGULATE_AV45 5
SUMMARYSUVR_WHOLECEREBNORM_AV45 8
PARIETAL_AV45 5
RH_PRECUNEUS_AV45 2
RH_SUPERIORTEMPORAL_AV45 1
LH_CAUDALMIDDLEFRONTAL_AV45 3
LH_ROSTRALANTERIORCINGULATE_AV45 6
RH_INFERIORTEMPORAL_AV45 2
LH_PRECENTRAL_AV45 2
LH_MEDIALORBITOFRONTAL_AV45 1
------- MRI --------------
CEREB_TCV 129
CEREB_TCC 152
CEREB_TCB 62
CEREB_GRAY 75
CEREB_WHITE 89
L_HIPPO 102
ST116CV 119
ST111CV 72
ST24CV 95
ST74CV 54
ST115CV 57
ST44CV 108
R_HIPPO 81
LHIPPO 120
ST88SV 77
ST57CV 64
ST40CV 107
TBM_1 57
ST85CV 86
ST35CV 105
TBM_2 87
ST94CV 85
RHIPPO 82
ST118CV 74
ST59CV 69
IPCA 70
ST91CV 113
ST12SV 120
ST103CV 110
ST29SV 95
ST55CV 87
ST31CV 125
ST99CV 73
ST119CV 70
ST52CV 103
ST32CV 127
ST26CV 107
ST90CV 107
ST83CV 92
ST60CV 92
ST71SV 90
ST56CV 90
------- RISKFACTORS --------------
AXHDACHE 11
AXSWEATN 8
AXDIZZY 5
MH18SURG 20
MH5RESP 31
AXDRYMTH 9
AXABDOMN 7
AXINSOMN 4
PTDOBYY 5
AXPALPIT 3
AXBREATH 5
AXDIARRH 462
AXCRYING 293
AXENERGY 257
AXELMOOD 9
AXCOUGH 5
AXDPMOOD 1401
HMSCORE 375
GDS 166
PTGENDER 82
MHPSYCH 128
AXRASH 4
AXANKLE 9
AXWANDER 9
HMSOMATC 3
MH7DERM 5
MH17MALI 10
AXCONSTP 11
AXVOMIT 5
MH11HEMA 1
AXDROWSY 1
------- PHENOTYPE --------------
MMSE 305
UW_EF 335
ADSP_EXF 287
UW_MEM 328
MOCA 319
CDR 240
ADSP_DX 215
ADSP_MEM 295
ADSP_LAN 309
ADSP_VSP 276
ADAS11 207
ADAS13 222

Total number of paths when the input started in the RISKFACTORS layer: 4618
------- GENETIC --------------
PHS 31
APOE_A2 6
APOE_A1 1
CIR 8
TOMM40_A2 16
APOE 7
------- MOLECULAR --------------
UPK_TAU 41
UPKelec_TAU 94
UPKelec_PTAU 45
UPK_PTAU 45
UGOT_PLASMAPTAU 30
UPplasma_AB42 9
UPK_AB42 12
FUJI_AB42 6
EUR_AB42/40 12
APP 13
UPKelec_AB42 7
BACE 57
FUJI_AB42/40 1
------- PET --------------
LH_CAUDALMIDDLEFRONTAL_AV45 10
ANGULR03_FDG 70
LH_ROSTRALANTERIORCINGULATE_AV45 10
RH_SUPERIORPARIETAL_AV45 31
RH_ROSTRALANTERIORCINGULATE_AV45 17
LH_FUSIFORM_AV45 10
LH_PARACENTRAL_AV45 10
LH_ENTORHINAL_AV45 13
LH_LATERALORBITOFRONTAL_AV45 12
RH_PARAHIPPOCAMPAL_AV45 16
RH_POSTCENTRAL_AV45 10
LH_LATERALOCCIPITAL_AV45 22
LH_SUPRAMARGINAL_AV45 20
TEMPORAL_AV45 21
LH_INFERIORTEMPORAL_AV45 10
HCI_2014_FDG 15
LH_TEMPORALPOLE_AV45 9
RH_FUSIFORM_AV45 15
RH_INFERIORPARIETAL_AV45 18
RH_CAUDALMIDDLEFRONTAL_AV45 5
RH_LATERALORBITOFRONTAL_AV45 3
LH_FRONTALPOLE_AV45 3
RH_PARSTRIANGULARIS_AV45 7
LH_MIDDLETEMPORAL_AV45 10
RH_PARSOPERCULARIS_AV45 28
RH_ISTHMUSCINGULATE_AV45 8
RH_PRECUNEUS_AV45 10
LH_INFERIORPARIETAL_AV45 8
LH_CUNEUS_AV45 5
SUMMARYSUVR_WHOLECEREBNORM_AV45 13
LH_TRANSVERSETEMPORAL_AV45 10
LH_SUPERIORFRONTAL_AV45 11
RH_ROSTRALMIDDLEFRONTAL_AV45 19
RH_FRONTALPOLE_AV45 5
LH_PRECENTRAL_AV45 6
ANGULR05_FDG 2
RH_ENTORHINAL_AV45 23
RH_PARACENTRAL_AV45 19
LH_CAUDALANTERIORCINGULATE_AV45 7
LH_SUPERIORPARIETAL_AV45 1
LH_LINGUAL_AV45 13
LH_ISTHMUSCINGULATE_AV45 4
CINGPSTL02_FDG 8
RH_MEDIALORBITOFRONTAL_AV45 11
LH_PARSOPERCULARIS_AV45 11
CINGPSTR12_FDG 1
RH_TEMPORALPOLE_AV45 23
LH_INSULA_AV45 9
LH_ROSTRALMIDDLEFRONTAL_AV45 7
LH_PARSORBITALIS_AV45 1
RH_INSULA_AV45 7
RH_SUPERIORTEMPORAL_AV45 7
COMPOSITE_AV45 16
TMPINFL02_FDG 2
RH_TRANSVERSETEMPORAL_AV45 2
CINGPSTL01_FDG 26
ANGULR04_FDG 10
CINGPST09_FDG 8
BRAAK34_SUVR 17
LH_SUPERIORTEMPORAL_AV45 9
CINGPST03_FDG 72
RH_INFERIORTEMPORAL_AV45 1
RH_CAUDALANTERIORCINGULATE_AV45 4
SUMMARYSUVR_COMPOSITE_REFNORM_AV45 6
TMPINFL11_FDG 2
MEAN_METAROI_PONSVERMIS 1
RH_PARSORBITALIS_AV45 1
RH_LATERALOCCIPITAL_AV45 10
HCI_FDG 4
LH_POSTERIORCINGULATE_AV45 5
FRONTAL_AV45 1
TMPINFL04_FDG 6
TMPINFR05_FDG 5
RH_LINGUAL_AV45 2
LH_PRECUNEUS_AV45 8
BRAAK56_SUVR 9
RH_MIDDLETEMPORAL_AV45 5
CINGPST07_FDG 297
ANGULR01_FDG 1
LH_PARSTRIANGULARIS_AV45 4
BRAAK1_SUVR 3
LH_MEDIALORBITOFRONTAL_AV45 1
RH_SUPRAMARGINAL_AV45 4
RH_CUNEUS_AV45 9
RH_POSTERIORCINGULATE_AV45 3
PARIETAL_AV45 9
LH_PARAHIPPOCAMPAL_AV45 10
------- MRI --------------
CEREB_TCV 142
ST26CV 24
ST24CV 30
RHIPPO 26
ST116CV 35
ST119CV 39
ST40CV 28
ST57CV 42
ST74CV 33
ST35CV 31
CEREB_GRAY 27
CEREB_WHITE 38
ST85CV 45
ST94CV 34
ST111CV 33
ST90CV 36
ST59CV 35
ST55CV 52
ST103CV 11
ST56CV 32
ST115CV 31
ST118CV 33
ST91CV 36
R_HIPPO 23
L_HIPPO 23
ST31CV 26
ST60CV 25
LHIPPO 25
ST52CV 25
ST99CV 38
ST88SV 5
ST32CV 50
ST83CV 10
ST12SV 14
CEREB_TCB 16
ST29SV 17
ST71SV 3
TBM_2 7
ST44CV 6
CEREB_TCC 109
------- RISKFACTORS --------------
AXNAUSEA 118
AXENERGY 1790
AXCRYING 933
AXDPMOOD 681
MHPSYCH 175
GDS 298
AXVOMIT 129
AXDIARRH 306
AXCONSTP 110
PTGENDER 87
AXABDOMN 119
HMHYPERT 164
AXSWEATN 154
AXDIZZY 149
AXBREATH 149
AXWANDER 120
AXDROWSY 151
AXELMOOD 144
HMSCORE 853
AXURNFRQ 108
AXDRYMTH 131
AXVISION 103
AXHDACHE 121
AXCOUGH 127
AXPALPIT 107
AXCHEST 94
AXURNDIS 104
HMEMOTIO 164
AXANKLE 100
AXMUSCLE 122
MH4CARD 151
AXRASH 99
AXINSOMN 85
HMNEURSG 154
AXFALL 83
HMONSET 99
HMNEURSM 141
HMSTROKE 125
HMSOMATC 106
HMSTEPWS 43
MH6HEPAT 21
PTDOBYY 100
MH9ENDO 28
PTHAND 15
MH17MALI 17
PTMARRY 19
MH3HEAD 17
MH10GAST 30
MH2NEURL 80
MH5RESP 135
MH18SURG 137
MH11HEMA 61
MH7DERM 81
MH8MUSCL 8
MH12RENA 12
MH13ALLE 11
MH14ALCH 177
MH16SMOK 159
MH15DRUG 50
------- PHENOTYPE --------------
MMSE 395
MOCA 419
CDR 373
ADSP_DX 363
ADSP_MEM 430
ADSP_EXF 408
ADSP_LAN 426
ADSP_VSP 382
ADAS11 363
ADAS13 374
UW_MEM 427
UW_EF 420

Total number of paths when the input started in the PHENOTYPE layer: 0
------- GENETIC --------------
------- MOLECULAR --------------
------- PET --------------
------- MRI --------------
------- RISKFACTORS --------------
------- PHENOTYPE --------------