In [28]:
import pickle
import ast
import pandas as pd
from collections import Counter

In [2]:
def load_pickle(file):
    """
    load a pickle file into a local variable
    can be a pandas dataframe or dictionary
    """
    pickle_in = open(file, "rb")
    pickle_file = pickle.load(pickle_in)
    pickle_in.close()
    return pickle_file

In [3]:
node_dict = load_pickle('node_dictionary.pickle')
top_paths = load_pickle(f'../results_pearson/network_paths/top_pathways.pickle')

# Negative Controls

In [4]:
n_permutations = 100
my_count = {}
for n in range(n_permutations):
    d = load_pickle(f'../results_pearson/negative_controls/vm/top_pathways_permuted{n}.pickle')
    for val in d.values():
        for el in val.values():
            for l in el:
                if str(l) in my_count:
                    my_count[str(l)] += 1
                else:
                    my_count[str(l)] = 1

Hay un problema con el dict que guarda los top paths: las keys son strings, no listas. Tengo que transformarlo.

In [5]:
rows = []
for key, el in my_count.items():
    key = ast.literal_eval(key)
    rows.append({"path": key, "count": el})

df = pd.DataFrame(rows)

In [6]:
df

                                  path  count
0        [APOE_A1, ANGULL01_FDG, MMSE]     13
1                 [APOE_A1, APP, MMSE]     20
2       [APOE_A1, FRTSUPL01_FDG, MMSE]      9
3        [APOE_A1, TS_RATIO_ADJ, MMSE]     27
4                      [APOE_A1, MMSE]     72
...                                ...    ...
915152     [MH12RENA, PTHAND, ADSP_DX]      1
915153    [MH12RENA, PTHAND, ADSP_MEM]      1
915154    [MH12RENA, PTHAND, ADSP_EXF]      1
915155    [MH12RENA, PTHAND, ADSP_LAN]      1
915156          [MH17MALI, UW_EF, CDR]      1

[915157 rows x 2 columns]

In [7]:
paths = []
for _, value in top_paths.items():
    for _, elements in value.items():
        for el in elements:
            paths.append(el)
paths_permuted = df.path.tolist()

In [36]:
print(len(paths))
print(len(paths_permuted))

30000
915157

In [8]:
not_in_permuted = [x for x in paths if x not in paths_permuted]
len(not_in_permuted)

18342

In [9]:
rows = []
for el in not_in_permuted:
    rows.append({"path": el, "count": 0})
df_append = pd.DataFrame(rows)
df_append

                              path  count
0         [APOE_A1, MH3HEAD, MMSE]      0
1        [APOE_A1, MH17MALI, MMSE]      0
2         [APOE_A1, MH5RESP, MMSE]      0
3       [APOE_A1, CEREB_TCC, MMSE]      0
4       [APOE_A1, TOTAL_CSF, MMSE]      0
...                            ...    ...
18337  [MH18SURG, MH10GAST, UW_EF]      0
18338   [MH18SURG, MH7DERM, UW_EF]      0
18339  [MH18SURG, MH16SMOK, UW_EF]      0
18340  [MH18SURG, MH12RENA, UW_EF]      0
18341  [MH18SURG, MH8MUSCL, UW_EF]      0

[18342 rows x 2 columns]

In [10]:
# concatenate the dataframes vertically
df = pd.concat([df, df_append], ignore_index=True)
df

                                  path  count
0        [APOE_A1, ANGULL01_FDG, MMSE]     13
1                 [APOE_A1, APP, MMSE]     20
2       [APOE_A1, FRTSUPL01_FDG, MMSE]      9
3        [APOE_A1, TS_RATIO_ADJ, MMSE]     27
4                      [APOE_A1, MMSE]     72
...                                ...    ...
933494     [MH18SURG, MH10GAST, UW_EF]      0
933495      [MH18SURG, MH7DERM, UW_EF]      0
933496     [MH18SURG, MH16SMOK, UW_EF]      0
933497     [MH18SURG, MH12RENA, UW_EF]      0
933498     [MH18SURG, MH8MUSCL, UW_EF]      0

[933499 rows x 2 columns]

In [13]:
df[df['count'] == 0]

                               path  count
915157     [APOE_A1, MH3HEAD, MMSE]      0
915158    [APOE_A1, MH17MALI, MMSE]      0
915159     [APOE_A1, MH5RESP, MMSE]      0
915160   [APOE_A1, CEREB_TCC, MMSE]      0
915161   [APOE_A1, TOTAL_CSF, MMSE]      0
...                             ...    ...
933494  [MH18SURG, MH10GAST, UW_EF]      0
933495   [MH18SURG, MH7DERM, UW_EF]      0
933496  [MH18SURG, MH16SMOK, UW_EF]      0
933497  [MH18SURG, MH12RENA, UW_EF]      0
933498  [MH18SURG, MH8MUSCL, UW_EF]      0

[18342 rows x 2 columns]

In [14]:
df[df['count'] <= 1]

                                                 path  count
127          [APOE_A2, UPplasma_AB42, AXBREATH, MMSE]      1
129            [APOE_A2, UPplasma_AB42, ST24TS, MMSE]      1
133          [APOE_A2, UPplasma_AB42, AXBREATH, MOCA]      1
136           [APOE_A2, UPplasma_AB42, AXCHEST, MOCA]      1
137     [APOE_A2, UPplasma_AB42, FUSFRML02_FDG, MOCA]      1
...                                               ...    ...
933494                    [MH18SURG, MH10GAST, UW_EF]      0
933495                     [MH18SURG, MH7DERM, UW_EF]      0
933496                    [MH18SURG, MH16SMOK, UW_EF]      0
933497                    [MH18SURG, MH12RENA, UW_EF]      0
933498                    [MH18SURG, MH8MUSCL, UW_EF]      0

[709446 rows x 2 columns]

In [15]:
path_pass = df[df['count'] == 0].path.tolist() # pathways that are present in less than 1% of the permuted pathways

In [16]:
rows = []
for el in path_pass:
    rows.append({"path": el, "source": el[0], "target": el[-1]})
df_pass = pd.DataFrame(rows)
df_pass

                              path    source target
0         [APOE_A1, MH3HEAD, MMSE]   APOE_A1   MMSE
1        [APOE_A1, MH17MALI, MMSE]   APOE_A1   MMSE
2         [APOE_A1, MH5RESP, MMSE]   APOE_A1   MMSE
3       [APOE_A1, CEREB_TCC, MMSE]   APOE_A1   MMSE
4       [APOE_A1, TOTAL_CSF, MMSE]   APOE_A1   MMSE
...                            ...       ...    ...
18337  [MH18SURG, MH10GAST, UW_EF]  MH18SURG  UW_EF
18338   [MH18SURG, MH7DERM, UW_EF]  MH18SURG  UW_EF
18339  [MH18SURG, MH16SMOK, UW_EF]  MH18SURG  UW_EF
18340  [MH18SURG, MH12RENA, UW_EF]  MH18SURG  UW_EF
18341  [MH18SURG, MH8MUSCL, UW_EF]  MH18SURG  UW_EF

[18342 rows x 3 columns]

In [17]:
df_pass.to_csv('pass_paths.csv', index=False) # paths que han pasado los negative controls

Paths identified when the input started at
- the genetics
- the molecular
- the PET
- the MRI
- the risk factors

In [ ]:
df_pass = pd.read_csv('pass_paths.csv')

In [43]:
for layer in node_dict.keys():
    df_temp = df_pass[df_pass.source.isin(node_dict[layer].copy())]
    print(f'Total number of paths when the input started in the {layer} layer: {len(df_temp)}')

    #Number of times nodes appear in the paths
    counters = [Counter(lst) for lst in df_temp.path.tolist()] # Create a Counter object for each list
    my_dict = dict(sum(counters, Counter())) # Merge the Counter objects into one dictionary

    for key, values in node_dict.items():
        print('-------', key, '--------------')
        for node, count in my_dict.items():
            if node in values:
                print(node, count)
    print('')

Total number of paths when the input started in the GENETIC layer: 557
------- GENETIC --------------
APOE_A1 90
APOE_A2 84
APOE 82
TOMM40_A1 79
TOMM40_A2 60
PHS 91
CIR 71
------- MOLECULAR --------------
------- PET --------------
MMPLS_FDG 2
------- MRI --------------
CEREB_TCC 40
TOTAL_CSF 40
------- RISKFACTORS --------------
MH3HEAD 83
MH17MALI 70
MH5RESP 84
MH16SMOK 51
MH2NEURL 31
MH13ALLE 43
MH10GAST 48
MH7DERM 60
PTDOBYY 5
------- PHENOTYPE --------------
MMSE 47
MOCA 52
CDR 43
ADSP_DX 44
ADSP_MEM 45
ADSP_EXF 45
ADSP_LAN 45
ADSP_VSP 45
ADAS11 46
ADAS13 46
UW_MEM 51
UW_EF 48

Total number of paths when the input started in the MOLECULAR layer: 1473
------- GENETIC --------------
CIR 6
APOE_A2 22
APOE 15
PHS 5
APOE_A1 1
------- MOLECULAR --------------
EUR_AB42 85
EUR_AB42/40 95
FUJI_AB42 100
FUJI_AB42/40 94
UGOT_PLASMAPTAU 97
TS_RATIO 132
TL 282
TS_RATIO_ADJ 208
BACE 125
UPKelec_TAU 55
UPKelec_PTAU 60
UPplasma_AB42 58
APP 102
UPK_AB42 83
UPK_TAU 83
UPK_PTAU 94
UPKelec_AB42 67
------- PET --------------
BRAAK56_SUVR 9
FRTMIDR01_FDG 5
TMPINFL02_FDG 100
TMPMIDL01_FDG 14
FRTMIDL01_FDG 94
BRAAK1_VOLUME 10
PARIINFL01_FDG 80
PRECUNL01_FDG 1
OCCMIDR01_FDG 92
OCCMIDL02_FDG 105
HCI_2014_FDG 6
CINGMIDR02_FDG 9
CINGPSTL01_FDG 1
TMPINFR01_FDG 86
FRTMIDL02_FDG 1
------- MRI --------------
TOTAL_CSF 46
CEREB_TCC 64
ST56SA 17
ST115SA 9
ST59SA 3
ST55SA 8
ST119SA 6
ST111SA 2
ST99SA 1
ST26SA 1
ST83TS 18
IPCA 30
ST118TA 4
ST59CV 6
ST74CV 7
ST118CV 6
ST60TA 4
ST59TA 1
ST31SA 3
ST60SA 3
ST59TS 11
ST118TS 33
ST85TS 12
ST56TS 5
TOTAL_GRAY 6
ST119TA 7
ST91TA 1
ST118SA 7
L_HIPPO 1
ST55TA 3
ST52TS 1
ST99TS 22
ST40TS 16
ST91TS 19
ST55TS 18
ST32TS 6
ST74TS 10
ST119TS 8
ST115TA 4
ST24TA 3
ST83TA 1
ST116CV 1
ST90SA 3
ST116SA 3
ST52SA 5
ST57SA 1
ST119CV 3
CEREB_TCV 2
ST74TA 4
TOTAL_HIPPO 4
ST115CV 1
ST24CV 1
ST99TA 1
ST111TS 2
ST26TA 4
ST24TS 2
ST24SA 1
ST56TA 2
ST111TA 1
ST31TA 1
------- RISKFACTORS --------------
MH12RENA 14
MH5RESP 72
MH2NEURL 46
MH17MALI 61
MH3HEAD 63
MH10GAST 51
MH7DERM 70
MH13ALLE 35
MH16SMOK 59
HMEMOTIO 55
AXANKLE 12
AXPALPIT 16
AXMUSCLE 11
AXHDACHE 13
AXVISION 8
AXNAUSEA 12
AXRASH 17
AXCHEST 8
AXABDOMN 2
AXDROWSY 4
AXURNFRQ 3
AXCONSTP 14
AXDIZZY 14
AXSWEATN 1
PTGENDER 15
AXENERGY 3
AXELMOOD 9
AXWANDER 5
AXCOUGH 23
GDS 8
AXDIARRH 20
AXBREATH 8
AXDPMOOD 21
MH9ENDO 3
MH6HEPAT 8
MH4CARD 1
------- PHENOTYPE --------------
MMSE 121
MOCA 138
CDR 132
ADSP_DX 118
ADSP_MEM 125
ADSP_EXF 123
ADSP_LAN 118
ADSP_VSP 126
ADAS11 137
ADAS13 144
UW_MEM 135
UW_EF 126

Total number of paths when the input started in the PET layer: 4860
------- GENETIC --------------
APOE 18
TOMM40_A1 4
APOE_A1 17
PHS 11
APOE_A2 9
TOMM40_A2 6
------- MOLECULAR --------------
UPplasma_AB42 2
FUJI_AB42/40 6
EUR_AB42 6
BACE 117
UPKelec_PTAU 36
UPK_PTAU 22
EUR_AB42/40 35
UGOT_PLASMAPTAU 5
FUJI_AB42 8
UPKelec_AB42 1
UPKelec_TAU 18
UPK_TAU 3
APP 1
TS_RATIO 1
------- PET --------------
MEAN_METAROI_PONSVERMIS 94
BRAAK1_SUVR 89
BRAAK1_VOLUME 102
FRTMIDL01_FDG 176
FRTSUPL02_FDG 65
BRAAK34_SUVR 96
BRAAK34_VOLUME 106
SUPMRGL01_FDG 349
PCA2_FDG 280
HCI_2014_FDG 113
OCCMIDL02_FDG 97
META_TEMPORAL_SUVR 108
META_TEMPORAL_VOLUME 77
BRAAK56_SUVR 110
BRAAK56_VOLUME 106
HIPPL01_FDG 82
FRTSUPL01_FDG 60
PARIINFR01_FDG 80
PRECUNR02_FDG 73
FRTMIDL02_FDG 73
PARAHIPL01_FDG 87
FUSFRML01_FDG 93
OCCMIDL01_FDG 83
ANGULL01_FDG 80
PARIINFL01_FDG 98
FRTMIDR01_FDG 107
TMPMIDL01_FDG 141
TMPINFL02_FDG 111
PRECUNL01_FDG 74
CINGPSTL01_FDG 111
CINGANTR02_FDG 94
PARAHIPR01_FDG 76
FRTSUPR01_FDG 34
OCCMIDR01_FDG 75
FUSFRMR01_FDG 80
ANGULR01_FDG 62
TMPMIDR01_FDG 143
SUPMRGR01_FDG 97
PRCUNSR01_FDG 72
TMPINFR01_FDG 62
CINGPSTL02_FDG 102
PRECUNL02_FDG 97
CINGMIDL02_FDG 31
FRTSMEDL02_FDG 81
FUSFRML02_FDG 99
TMPMIDL02_FDG 46
CINGANTL02_FDG 71
PLSFDG01_FDG 92
FRTMIDOR02_FDG 67
FRTMIDR02_FDG 102
FRTSUPR02_FDG 36
ANGULR02_FDG 89
SROI_FDG 88
INSULAR02_FDG 104
ANGULL02_FDG 60
PARIINFR02_FDG 80
CINGMIDR02_FDG 91
TMPMIDR02_FDG 135
TMPPOSR02_FDG 152
MMPLS_FDG 51
RECTUSR02_FDG 82
HCI_FDG 104
------- MRI --------------
CEREB_TCC 195
TOTAL_CSF 214
ST99TA 8
ST111CV 15
ST56SA 23
CEREB_TCV 22
ST59SA 22
ST111SA 13
TOTAL_GRAY 8
ST74TA 9
ST31SA 6
ST116SA 10
ST91CV 9
ST85TA 5
ST111TS 9
ST99SA 8
ST85SA 6
ST57TS 8
ST90TS 1
ST118TA 9
ST26SA 5
ST26CV 4
ST59CV 7
ST83SA 9
ST52TA 6
ST31CV 7
ST118CV 4
ST40CV 5
ST83TS 13
RHIPPO 1
ST32TS 5
ST55TS 3
ST40TS 1
ST99TS 1
IPCA 36
ST90SA 10
ST56CV 5
ST55SA 7
ST32SA 1
ST60TS 5
CEREB_WHITE 10
ST91SA 5
ST24TS 10
L_HIPPO 4
ST119SA 15
ST60SA 2
ST32TA 4
ST26TA 4
ST24SA 2
ST85TS 9
ST57SA 4
ST119CV 3
ST116CV 13
ST74CV 5
ST116TA 3
ST115TS 3
ST74SA 11
ST99CV 4
TBM_1 4
ST52TS 7
CEREB_TCB 6
ST116TS 2
ST57TA 10
ST91TA 8
ST59TA 1
CEREB_GRAY 5
TOTAL_WHITE 5
ST85CV 8
ST83CV 8
R_HIPPO 4
ST90TA 3
ST24CV 5
ST119TA 2
ST24TA 4
ST119TS 8
ST56TS 3
ST90CV 6
ST31TA 3
ST55TA 4
ST57CV 3
ST115CV 2
ST118SA 1
------- RISKFACTORS --------------
MH3HEAD 424
MH16SMOK 92
MH5RESP 595
MH17MALI 198
MH7DERM 479
MH13ALLE 413
MH10GAST 407
MH8MUSCL 43
HMEMOTIO 202
MH18SURG 11
PTGENDER 10
AXURNDIS 22
AXSWEATN 20
MH15DRUG 8
AXRASH 31
MH12RENA 192
MH2NEURL 311
PTMARRY 2
MH14ALCH 4
MH6HEPAT 19
AXDIARRH 21
GDS 3
AXABDOMN 9
AXDIZZY 39
AXHDACHE 43
AXINSOMN 11
AXANKLE 21
AXCONSTP 7
AXENERGY 4
AXURNFRQ 20
AXNAUSEA 6
AXVOMIT 34
AXCOUGH 3
AXBREATH 2
AXMUSCLE 21
AXFALL 6
MHPSYCH 1
AXPALPIT 5
AXVISION 2
PTHAND 9
AXCHEST 4
AXELMOOD 8
MH9ENDO 4
AXDPMOOD 3
------- PHENOTYPE --------------
MMSE 406
ADSP_VSP 418
MOCA 415
CDR 420
ADSP_DX 419
ADSP_MEM 411
ADSP_EXF 422
ADSP_LAN 440
ADAS11 424
ADAS13 429
UW_MEM 419
UW_EF 439

Total number of paths when the input started in the MRI layer: 7717
------- GENETIC --------------
APOE 16
APOE_A1 23
APOE_A2 10
TOMM40_A1 2
CIR 7
PHS 9
------- MOLECULAR --------------
UPplasma_AB42 4
FUJI_AB42 6
EUR_AB42 1
UPK_PTAU 4
UPKelec_PTAU 11
------- PET --------------
FRTMIDL02_FDG 554
TMPMIDR01_FDG 496
HCI_2014_FDG 33
MEAN_METAROI_PONSVERMIS 13
ANGULL02_FDG 22
BRAAK1_VOLUME 4
FRTSMEDL02_FDG 1
OCCMIDL01_FDG 1
TMPMIDR02_FDG 10
OCCMIDR01_FDG 3
CINGMIDR02_FDG 3
------- MRI --------------
CEREB_TCV 87
TOTAL_CSF 850
CEREB_TCC 875
CEREB_TCB 113
ST56SA 93
L_HIPPO 127
ST116TS 78
ST40SA 77
ST90SA 72
ST74TS 89
ST99TS 111
ST118TS 100
ST91TS 104
ST74SA 84
ST56TS 101
CEREB_WHITE 103
ST99SA 78
ST91SA 69
ST52CV 72
ST85TA 89
ST32TS 87
CEREB_GRAY 122
ST24TS 90
ST119TS 93
ST56TA 86
ST31SA 79
ST55TA 97
ST83TA 80
ST26TA 88
ST57SA 80
ST52SA 76
R_HIPPO 128
TOTAL_GRAY 110
TOTAL_HIPPO 128
ST32SA 64
ST119SA 74
ST85SA 64
ST116SA 65
ST57TS 61
ST115SA 88
IPCA 58
ST118SA 84
ST59SA 69
ST111SA 85
ST40TA 74
ST26SA 84
ST57CV 74
ST59CV 64
ST90CV 64
ST85CV 78
ST55SA 63
ST60TS 90
ST60SA 76
LHIPPO 56
ST74CV 73
ST55CV 70
ST118CV 75
ST24CV 73
ST40CV 70
ST115TS 117
ST26TS 104
ST59TA 84
ST91TA 83
ST90TA 61
ST32CV 59
ST85TS 93
TOTAL_WHITE 103
ST56CV 76
TBM_1 48
TBM_2 85
RHIPPO 39
ST111CV 72
ST111TA 88
ST111TS 60
ST115CV 72
ST115TA 82
ST116CV 67
ST116TA 64
ST118TA 88
ST59TS 74
ST119CV 79
ST119TA 69
ST24SA 53
ST24TA 79
ST26CV 70
ST31CV 52
ST31TA 50
ST31TS 59
ST32TA 57
ST40TS 53
ST52TA 60
ST52TS 77
ST55TS 88
ST57TA 77
ST60CV 84
ST60TA 79
ST74TA 70
ST83CV 69
ST83SA 68
ST83TS 64
ST90TS 63
ST91CV 77
ST99CV 78
ST99TA 62
------- RISKFACTORS --------------
MH3HEAD 810
MH13ALLE 386
MH5RESP 1124
MH10GAST 685
AXCONSTP 55
PTMARRY 11
AXSWEATN 44
AXELMOOD 10
AXDIARRH 12
AXHDACHE 22
AXCRYING 12
AXNAUSEA 8
PTHAND 18
HMSTEPWS 25
AXBREATH 2
AXCOUGH 23
HMNEURSG 22
AXENERGY 9
MH15DRUG 9
AXFALL 24
AXURNDIS 6
MH18SURG 9
GDS 10
MH6HEPAT 10
AXANKLE 1
MH17MALI 554
MH7DERM 609
MH12RENA 73
MH2NEURL 536
MH16SMOK 250
AXVOMIT 1
MH8MUSCL 6
AXDRYMTH 1
AXMUSCLE 1
PTDOBYY 18
MH11HEMA 4
HMEMOTIO 8
AXCHEST 1
------- PHENOTYPE --------------
MMSE 636
MOCA 753
CDR 598
ADSP_DX 640
ADSP_MEM 629
ADSP_EXF 633
ADSP_LAN 691
ADSP_VSP 612
ADAS11 616
ADAS13 629
UW_MEM 689
UW_EF 702

Total number of paths when the input started in the RISKFACTORS layer: 3735
------- GENETIC --------------
APOE_A2 15
APOE_A1 11
PHS 26
APOE 17
------- MOLECULAR --------------
UPKelec_TAU 2
UPKelec_PTAU 8
UGOT_PLASMAPTAU 10
EUR_AB42 1
EUR_AB42/40 42
UPK_PTAU 2
UPK_TAU 10
UPK_AB42 1
FUJI_AB42 1
FUJI_AB42/40 1
------- PET --------------
FRTMIDL02_FDG 152
TMPMIDL01_FDG 22
META_TEMPORAL_VOLUME 2
PRECUNR02_FDG 1
ANGULL01_FDG 9
BRAAK56_VOLUME 3
BRAAK1_VOLUME 5
OCCMIDL01_FDG 3
BRAAK34_SUVR 16
FRTMIDR01_FDG 19
BRAAK56_SUVR 17
PRECUNL01_FDG 1
FUSFRML01_FDG 20
BRAAK1_SUVR 21
FUSFRMR01_FDG 17
CINGPSTL01_FDG 7
FRTSMEDL02_FDG 3
PARAHIPR01_FDG 1
OCCMIDR01_FDG 58
HCI_2014_FDG 35
MEAN_METAROI_PONSVERMIS 2
CINGMIDR02_FDG 17
FUSFRML02_FDG 3
META_TEMPORAL_SUVR 10
CINGMIDL02_FDG 1
RECTUSR02_FDG 14
FRTSUPL02_FDG 1
HIPPL01_FDG 7
------- MRI --------------
TOTAL_CSF 291
CEREB_TCC 258
ST83TS 2
ST32TS 33
ST85TS 21
ST115SA 11
ST57TS 8
ST59TA 5
IPCA 30
ST119TS 3
ST111TS 6
ST52TA 11
ST40SA 6
ST85TA 7
ST31TS 8
ST115CV 1
ST111SA 13
ST115TA 5
ST57TA 8
ST59TS 14
ST40TS 12
ST57SA 16
CEREB_TCB 4
ST91SA 7
ST40TA 4
ST60TS 6
ST90TS 2
ST32CV 8
CEREB_WHITE 8
ST26CV 5
ST32TA 9
ST116CV 5
ST56CV 5
ST111CV 1
ST74TA 10
ST83CV 1
ST118TS 15
ST74TS 5
ST55TS 9
ST91TS 15
ST99TS 18
ST26TS 1
ST118SA 2
ST59SA 6
ST31SA 4
ST56TA 2
RHIPPO 4
ST99TA 2
ST83SA 13
ST74SA 13
ST52SA 10
ST59CV 5
ST55CV 4
ST90CV 4
ST99CV 2
ST55SA 7
ST119SA 10
ST116SA 7
CEREB_TCV 5
ST24SA 5
LHIPPO 3
ST56SA 1
ST91TA 1
ST119TA 3
ST24TS 15
ST31CV 11
ST74CV 4
ST99SA 5
ST55TA 6
ST118CV 3
ST60SA 5
ST85CV 4
ST40CV 2
ST57CV 4
L_HIPPO 3
ST111TA 2
------- RISKFACTORS --------------
AXNAUSEA 45
MH10GAST 495
AXPALPIT 28
MH17MALI 138
AXVOMIT 58
AXDIZZY 69
AXDRYMTH 39
AXMUSCLE 151
AXFALL 23
AXDIARRH 43
MH13ALLE 523
AXANKLE 137
AXCONSTP 68
MH12RENA 361
AXABDOMN 45
AXINSOMN 77
AXVISION 60
AXSWEATN 50
MH5RESP 467
MH8MUSCL 151
MH7DERM 536
AXCHEST 27
AXRASH 104
AXENERGY 114
MH2NEURL 433
AXHDACHE 122
AXDROWSY 125
HMNEURSM 88
MHPSYCH 115
MH18SURG 93
AXCOUGH 65
MH11HEMA 107
AXBREATH 85
AXURNFRQ 122
AXURNDIS 15
MH3HEAD 392
PTGENDER 103
AXDPMOOD 26
AXCRYING 9
AXELMOOD 18
AXWANDER 22
HMONSET 43
HMSTEPWS 32
HMSOMATC 52
HMEMOTIO 37
HMHYPERT 40
MH4CARD 68
HMSCORE 114
HMSTROKE 27
HMNEURSG 149
GDS 42
PTMARRY 126
PTDOBYY 102
PTHAND 29
PTEDUCAT 47
MH16SMOK 216
MH6HEPAT 76
MH9ENDO 60
MH14ALCH 108
MH15DRUG 22
------- PHENOTYPE --------------
MMSE 330
MOCA 389
CDR 290
ADSP_DX 309
ADSP_MEM 343
ADSP_EXF 325
ADSP_LAN 323
ADSP_VSP 337
ADAS11 332
ADAS13 310
UW_MEM 353
UW_EF 332

Total number of paths when the input started in the PHENOTYPE layer: 0
------- GENETIC --------------
------- MOLECULAR --------------
------- PET --------------
------- MRI --------------
------- RISKFACTORS --------------
------- PHENOTYPE --------------