In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
pd.read_csv('../capas_def/PHENOTYPE.csv')

,RID,ADSP_ClinDiag,ADAS11,ADAS13,MMSE,MOCA,CDR,UW_Mem,UW_Exec,ADSP_Mem,ADSP_Exec,ADSP_Lang,ADSP_Vispatial
0,1,NaN,NaN,NaN,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1.0,10.67,19.67,28.0,17.0,0.0,486.0,91.000,0.277,0.254,0.293,-0.333
2,3,3.0,22.00,31.00,20.0,NaN,1.0,-848.0,-1.112,-1.068,-0.670,-0.516,-0.237
3,4,2.0,14.33,21.33,27.0,NaN,0.5,96.0,-929.000,-0.014,-0.603,0.487,-0.074
4,5,1.0,8.67,14.67,29.0,NaN,0.0,589.0,338.000,0.520,0.577,0.345,0.258
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3862,7029,NaN,NaN,NaN,30.0,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
3863,7030,NaN,NaN,NaN,29.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3864,7031,NaN,NaN,NaN,27.0,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
3865,7032,NaN,NaN,NaN,27.0,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN
3866,7033,NaN,NaN,NaN,26.0,NaN,0.5,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def visit(visit_str):
    if visit_str == 'bl': #baseline
        return 0
    elif visit_str == 'sc': #screen (normalmente 1 mes antes del baseline)
        return 0
    elif visit_str == 'f': #fail
        return -1
    else:
        try:
            visit_num = visit_str.replace('m', '')
            visit_num = float(visit_num)
            return visit_num
        except:
            return None

In [4]:
temp = pd.read_csv('../archivos_originales/clinic/MMSE.csv')
df = temp[['RID', 'VISCODE2', 'MMSCORE']].copy()
df.rename(columns={"MMSCORE": "MMSE"}, inplace=True)
df = df[df['MMSE'].notna()]
df['VISCODE2'] = df['VISCODE2'].astype('str')
df['Visit'] = df['VISCODE2'].apply(visit)
df.drop(columns=['VISCODE2'], inplace=True)

c:\Users\campa\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (8) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
temp = pd.read_csv('../archivos_originales/clinic/MOCA.csv')
df2 = temp[['RID', 'VISCODE2', 'MOCA']].copy()
df2 = df2[df2['MOCA'].notna()]
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [6]:
temp = pd.read_csv('../archivos_originales/clinic/CDR.csv')
df2 = temp[['RID', 'VISCODE2', 'CDGLOBAL']].copy()
df2.rename(columns={"CDGLOBAL": "CDR"}, inplace=True)
df2 = df2[df2['CDR'].notna()]
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [7]:
temp = pd.read_csv('../archivos_originales/clinic/ADSP.csv')
df2 = temp[['RID', 'VISCODE2', 'DX', 'PHC_MEM', 'PHC_EXF', 'PHC_LAN', 'PHC_VSP']].copy()
df2.rename(columns={"DX": "ADSP_DX", 'PHC_MEM': 'ADSP_MEM', 'PHC_EXF': 'ADSP_EXF', 'PHC_LAN': 'ADSP_LAN', 'PHC_VSP': 'ADSP_VSP'}, inplace=True)
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [8]:
temp = pd.read_csv('../archivos_originales/clinic/ADASSCORES.csv')
df2 = temp[['RID', 'VISCODE', 'TOTAL11', 'TOTALMOD']].copy()
df2.rename(columns={"TOTAL11": "ADAS11", 'TOTALMOD': 'ADAS13'}, inplace=True)
df2['VISCODE'] = df2['VISCODE'].astype('str')
df2['Visit'] = df2['VISCODE'].apply(visit)
df2.drop(columns=['VISCODE'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [9]:
temp = pd.read_csv('../archivos_originales/clinic/UWNPSYCHSUM.csv')
df2 = temp[['RID', 'VISCODE2', 'ADNI_MEM', 'ADNI_EF']].copy()
df2.rename(columns={"ADNI_MEM": "UW_MEM", 'ADNI_EF': 'UW_EF'}, inplace=True)
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [10]:
cols = list(df.columns)
df = df[['RID', 'Visit', 'MMSE', 'MOCA', 'CDR', 'ADSP_DX', 'ADSP_MEM', 'ADSP_EXF', 'ADSP_LAN', 'ADSP_VSP', 'ADAS11', 'ADAS13', 'UW_MEM', 'UW_EF']]
df = df.sort_values('RID')
df

,RID,Visit,MMSE,MOCA,CDR,ADSP_DX,ADSP_MEM,ADSP_EXF,ADSP_LAN,ADSP_VSP,ADAS11,ADAS13,UW_MEM,UW_EF
0,1,-1.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0.0,28.0,NaN,0.0,1.0,0.277,0.254,0.293,NaN,NaN,NaN,486.000,91.000
2,2,6.0,28.0,NaN,0.0,1.0,0.237,0.278,0.535,-0.333,10.67,19.67,581.000,88.000
3,2,36.0,29.0,NaN,0.0,1.0,0.344,0.419,0.535,NaN,12.00,20.00,405.000,88.000
4,2,60.0,28.0,NaN,0.0,1.0,0.101,0.066,0.620,0.264,NaN,NaN,352.000,-294.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13422,6640,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.724,-615.000
13423,6653,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.143,431.000
13424,6733,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.595
13425,6800,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.414,-1.437
13426,6846,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,315.000,96.000

In [ ]:
df.to_csv('clinic.csv', index=False)