In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
pd.read_csv('../capas_def/BIOMARKERS.csv')

,RID,UPK9_TAU,UPK10_TAU,UPK12_TAU,UPENN17_TAU,UPENNPLASMA_AB42,UPK9_AB,UPK10_AB42,UPK12_AB42,BACE1,APP,EUR_AB42,EUR_AB42/40,FUJI_AB42,FUJI_AB42/40,UPENN17_AB42,UPENN17_AB42/40,UGOT_PTAU181_plasma,UPK9_PTAU_csf,UPK10_PTAU_csf,UPK12_PTAU_csf,TL_SCG,TL
0,1,NaN,NaN,NaN,NaN,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.00,0.000,0.000,0.000,0.000
1,2,NaN,NaN,NaN,NaN,50.9,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,11.939,0.00,0.000,0.000,0.000,0.000
2,3,239.7,357.864,104.139,NaN,58.1,741.5,-69.897,114.613,39.0,3728.0,268.305,298.722,296.379,123.045,0.0,0.0,177.815,22.83,-15.376,276.938,296.379,123.045
3,4,153.1,288.762,5.682,NaN,59.8,1501.0,-63.827,117.609,38.0,2026.0,264.542,284.136,301.284,132.222,0.0,0.0,151.851,13.29,-133.724,271.684,301.284,132.222
4,5,337.0,NaN,NaN,NaN,46.7,547.3,0.000,0.000,55.0,3785.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,33.43,0.000,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7240,7246,NaN,NaN,NaN,NaN,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.00,0.000,0.000,0.000,0.000
7241,7247,NaN,NaN,NaN,NaN,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.00,0.000,0.000,0.000,0.000
7242,7248,NaN,NaN,NaN,NaN,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.00,0.000,0.000,0.000,0.000
7243,7249,NaN,NaN,NaN,NaN,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.00,0.000,0.000,0.000,0.000
7244,7250,NaN,NaN,NaN,NaN,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.00,0.000,0.000,0.000,0.000

In [3]:
def visit(visit_str):
    if visit_str == 'bl': #baseline
        return 0
    elif visit_str == 'sc': #screen (normalmente 1 mes antes del baseline)
        return 0
    elif visit_str == 'f': #fail
        return -1
    else:
        try:
            visit_num = visit_str.replace('m', '')
            visit_num = float(visit_num)
            return visit_num
        except:
            return None

In [4]:
temp = pd.read_csv('../archivos_originales/molecular/ADNI_EUROIMMUN.csv')
df = temp[['RID', 'VISCODE2', 'BETA_AMYLOID_1_42', 'BETA_AMYLOID_42_40']].copy()
df.rename(columns={"BETA_AMYLOID_1_42": "EUR_AB42", 'BETA_AMYLOID_42_40': 'EUR_AB42/40'}, inplace=True)
df['VISCODE2'] = df['VISCODE2'].astype('str')
df['Visit'] = df['VISCODE2'].apply(visit)
df.drop(columns=['VISCODE2'], inplace=True)

In [5]:
temp = pd.read_csv('../archivos_originales/molecular/FUJIREBIOABETA.csv')
df2 = temp[['RID', 'VISCODE2', 'ABETA42', 'ABETA42_40']].copy()
df2.rename(columns={"ABETA42": "FUJI_AB42", 'ABETA42_40': 'FUJI_AB42/40'}, inplace=True)
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [6]:
temp = pd.read_csv('../archivos_originales/molecular/UGOTPTAU181_06_18_20.csv')
df2 = temp[['RID', 'VISCODE2', 'PLASMAPTAU181']].copy()
df2.rename(columns={"PLASMAPTAU181": "UGOT_PLASMAPTAU"}, inplace=True)
df2 = df2[df2['UGOT_PLASMAPTAU'].notna()]
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [7]:
temp = pd.read_csv('../archivos_originales/molecular/TS_RATIO_ADJ.csv')
df2 = temp[['RID', 'VISCODE2', 'TS_RATIO', 'TS_RATIO_ADJ', 'TL_BP_ADJ']].copy()
df2.rename(columns={"TL_BP_ADJ": "TL"}, inplace=True)
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [8]:
temp = pd.read_csv('../archivos_originales/molecular/BACE.csv', sep=';')
df2 = temp[['Subject ID', 'Visit #', 'CSF BACE (pM)', 'CSF sAPPβ (pM)']].copy()
df2.rename(columns={'Subject ID': 'RID', 'CSF BACE (pM)': 'BACE', "CSF sAPPβ (pM)": "APP"}, inplace=True)
df2['RID'] = df['RID'].replace("*", "")
df2['RID'] = df2['RID'].astype('int')
df2['Visit #'] = df2['Visit #'].astype('str')
df2['Visit'] = df2['Visit #'].apply(visit)
df2.drop(columns=['Visit #'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [9]:
temp = pd.read_csv('../archivos_originales/molecular/UPENNBIOMK_MASTER.csv')
temp = temp[temp.BATCH == 'MEDIAN'].copy()
df2 = temp[['RID', 'VISCODE', 'ABETA', 'TAU', 'PTAU']].copy()
df2.rename(columns={"ABETA": "UPK_AB42", 'TAU': 'UPK_TAU', 'PTAU': 'UPK_PTAU'}, inplace=True)
df2['VISCODE'] = df2['VISCODE'].astype('str')
df2['Visit'] = df2['VISCODE'].apply(visit)
df2.drop(columns=['VISCODE'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [10]:
temp = pd.read_csv('../archivos_originales/molecular/UPENNBIOMK9_04_19_17.csv')
temp = temp[['RID', 'VISCODE2', 'ABETA', 'TAU', 'PTAU']].copy()
temp.rename(columns={'ABETA': 'ABETA42'}, inplace=True)
temp2 = pd.read_csv('../archivos_originales/molecular/UPENNBIOMK10_07_29_19.csv')
temp2 = temp2[['RID', 'VISCODE2', 'ABETA42', 'TAU', 'PTAU']].copy()
temp3 = pd.read_csv('../archivos_originales/molecular/UPENNBIOMK12_01_04_21.csv')
temp3 = temp3[['RID', 'VISCODE2', 'ABETA', 'TAU', 'PTAU']].copy()
temp3.rename(columns={'ABETA': 'ABETA42'}, inplace=True)

def clean(col_str):
    if '>' in col_str:
        return None
temp[['ABETA42', 'TAU', 'PTAU']] = temp[['ABETA42', 'TAU', 'PTAU']].apply(clean)
temp[['ABETA42', 'TAU', 'PTAU']] = temp[['ABETA42', 'TAU', 'PTAU']].apply(pd.to_numeric)

temp = pd.merge(temp, temp2, on=['RID', 'VISCODE2', 'ABETA42', 'TAU', 'PTAU'], how='outer')
temp = pd.merge(temp, temp3, on=['RID', 'VISCODE2', 'ABETA42', 'TAU', 'PTAU'], how='outer')

df2 = temp[['RID', 'VISCODE2', 'ABETA42', 'TAU', 'PTAU']].copy()
df2.rename(columns={"ABETA42": "UPKelec_AB42", 'TAU': 'UPKelec_TAU', 'PTAU': 'UPKelec_PTAU'}, inplace=True)
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [11]:
temp = pd.read_csv('../archivos_originales/molecular/UPENNPLASMA.csv')
df2 = temp[['RID', 'VISCODE', 'AB42']].copy()
df2 = df2[df2['AB42'].notna()]
df2.rename(columns={"AB42": "UPplasma_AB42"}, inplace=True)
df2['VISCODE'] = df2['VISCODE'].astype('str')
df2['Visit'] = df2['VISCODE'].apply(visit)
df2.drop(columns=['VISCODE'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [12]:
df = df[['RID', 'Visit', 'EUR_AB42', 'EUR_AB42/40', 'FUJI_AB42', 'FUJI_AB42/40', 'UGOT_PLASMAPTAU', 'TS_RATIO', 'TS_RATIO_ADJ', 'TL', 'BACE',
'APP', 'UPK_AB42', 'UPK_TAU', 'UPK_PTAU', 'UPKelec_AB42', 'UPKelec_TAU', 'UPKelec_PTAU', 'UPplasma_AB42']]
df = df.sort_values(['RID', 'Visit'])
df

,RID,Visit,EUR_AB42,EUR_AB42/40,FUJI_AB42,FUJI_AB42/40,UGOT_PLASMAPTAU,TS_RATIO,TS_RATIO_ADJ,TL,BACE,APP,UPK_AB42,UPK_TAU,UPK_PTAU,UPKelec_AB42,UPKelec_TAU,UPKelec_PTAU,UPplasma_AB42
6406,2,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.9
6407,2,36.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.1
1012,2,60.0,NaN,NaN,NaN,NaN,11.939,0.84,0.89,5415.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1013,2,72.0,NaN,NaN,NaN,NaN,12.936,0.77,0.80,5193.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1014,2,84.0,NaN,NaN,NaN,NaN,13.563,0.87,0.87,5375.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6401,6848,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1393.0,172.4,14.82,NaN
6402,6850,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1061.0,408.7,30.82,NaN
6403,6861,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1349.0,217.9,19.76,NaN
6404,6871,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1649.0,200.4,16.93,NaN
6405,6877,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,529.3,306.8,28.07,NaN

In [13]:
df.to_csv('molecular.csv', index=False)