In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
pd.read_csv('../capas_def/PET.csv')

,RID,HCI_FDG,R_Hip/Pons_FDG,L_Hip/Pons_FDG,METAROI_MEAN_FDG,METAROI_MAX_FDG,METAROI_STDEV_FDG,Glu_Hipp_L_AV45,Glu_ParaHipp_L_AV45,Glu_Fus_L_AV45,Glu_Occ_M_L_AV45,Glu_Ang_L_AV45,Glu_Parietal_I_L_AV45,Glu_SupraMarg_L_AV45,Glu_Precun_L_AV45,Glu_Cing_P_L_AV45,Glu_ParaHipp_R_AV45,Glu_Front_S_R_AV45,Glu_Occ_M_R_AV45,Glu_Fus_R_AV45,Glu_Ang_R_AV45,Glu_Parietal_I_R_AV45,Glu_SupraMarg_R_AV45,Glu_Precun_R_AV45,Glu_Temp_I_R_AV45,Glu_Front_S_L_AV45,Glu_Front_M_L_AV45,Glu_Cing_M_L_AV45,Glu_Front_Medial_L_AV45,Glu_Temp_M_L_AV45,Glu_Temp_I_L_AV45,Glu_Cing_A_L_AV45,Glu_Front_M_Orb_R_AV45,Glu_Front_M_R_AV45,Glu_Temp_M_R_AV45,Glu_Insula_R_AV45,Glu_Temp_Pole_S_R_AV45,Glu_Cing_A_R_AV45,Glu_Cing_M_R_AV45,Glu_Rectus_R_AV45,Temp_S_R_AV45,Temp_M_L_AV45,Temp_M_R_AV45,Temp_I_L_AV45,Temp_I_R_AV45,Parietal_I_L_AV45,Parietal_I_R_AV45,Precun_L_AV45,Precun_R_AV45,Cing_A_AV45,Cing_M_AV45,Cing_P_AV45,Ang_R_AV45,SupraMarg_L_AV45,Calca_L_AV45,Lingual_L_AV45,Cereb_8_L_AV45,Cereb_Crus2_L_AV45,Fus_L_AV45,Fus_R_AV45,Occ_M_R_AV45,Hipp_R_AV45,Occ_M_L_AV45,Cing_P_L_AV45,Cing_P/M_R_AV45,HCI_ADNI1_AV45,Glu_CIN129_AV45,Glu_PAR129_AV45,post_cing_FDG_AV45,temp_FDG_AV45,precun_AV-45_AV45,AVfdgPLS_AV45,AV_SSM_AV45,PLS_FDG_PET_AV45,Hypomet_AV45,sROI_val_AV45,Braak1_mean_AV1451,Braak1_size_AV1451,Braak34_mean_AV1451,Braak34_size_AV1451,MetatempROI_mean_AV1451,MetatempROI_size_AV1451,Braak56_mean_AV1451,Braak56_size_AV1451,f18_entorhi_suvr,f18_I_temp_suvr,f18_tau_metaroi
0,1,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,11.3802,112.941,111.765,9.368193e+08,1.297328e+09,107473515.0,118.423,124.189,127.127,1.7672,188.702,174.0040,184.0030,192.0380,161.486,126.803,199.549,168.205,141.414,211.981,200.172,147.705,2.1626,174.573,153.126,166.633,1.9076,162.655,148.7910,120.841,163.155,167.896,191.644,179.171,158.182,150.296,145.585,208.713,127.548,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,147.671,122.288,117.5410,122.386,0.0,0.0,0.0,4.75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.2033,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,212.0660,836.957,586.957,1.101949e+09,1.414214e+09,136263315.0,960.787,982.463,992.775,139.3470,163.597,162.8970,165.8850,1.7647,178.213,893.697,193.984,152.274,110.824,185.249,191.291,144.804,200.8980,164.672,144.001,160.455,195.3160,173.124,1.1576,126.861,176.883,185.014,188.704,149.179,139.697,131.732,172.644,204.912,159.249,145.988,113.046,1.3553,112.063,129.457,132.039,177.948,217.136,225.784,143.205,143.929,162.723,139.716,107.366,0.0,0.0,0.0,0.0,0.000,119.159,120.8410,0.000,0.0,0.0,0.0,9.51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.1339,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,8.3593,978.947,989.474,1.019335e+09,1.275399e+08,106062438.0,124.698,139.355,130.774,169.8580,191.678,1.8724,1.8219,196.8540,181.998,122.501,197.282,140.492,149.819,180.292,182.884,134.968,198.8870,153.375,155.456,170.555,199.7430,171.937,143.4360,133.852,173.717,175.217,190.373,154.993,158.485,148.555,166.313,205.052,147.832,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,155.539,133.294,1.2467,137.728,0.0,0.0,0.0,4.55,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.2137,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4168,7042,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4169,7043,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4170,7044,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4171,7045,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4172,7046,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.000,0.000,0.0000,0.000,0.0000,0.0000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.0000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.000,0.000,0.0000,0.000,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
def visit(visit_str):
    if visit_str == 'bl': #baseline
        return 0
    elif visit_str == 'sc': #screen (normalmente 1 mes antes del baseline)
        return 0
    elif visit_str == 'f': #fail
        return -1
    else:
        try:
            visit_num = visit_str.replace('m', '')
            visit_num = float(visit_num)
            return visit_num
        except:
            return None

In [4]:
temp = pd.read_csv('../archivos_originales/pet/UCBERKELEYFDG.csv')
temp1 = temp[temp.ROINAME == 'metaroi']
temp2 = temp[temp.ROINAME == 'pons-vermis']

df = temp1[['RID', 'VISCODE2', 'MEAN']].copy()
df.rename(columns={"MEAN": "MEAN_METAROI"}, inplace=True)
df['VISCODE2'] = df['VISCODE2'].astype('str')
df['Visit'] = df['VISCODE2'].apply(visit)
df.drop(columns=['VISCODE2'], inplace=True)

df2 = temp2[['RID', 'VISCODE2', 'MEAN']].copy()
df2.rename(columns={"MEAN": "MEAN_PONSVERMIS"}, inplace=True)
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

df['MEAN_METAROI_PONSVERMIS'] = df['MEAN_METAROI']/df['MEAN_PONSVERMIS']
df.drop(columns=['MEAN_METAROI', 'MEAN_PONSVERMIS'], inplace=True)

In [5]:
temp = pd.read_csv('../archivos_originales/pet/UCBERKELEYAV1451_04_26_22.csv')
df2 = temp[['RID', 'VISCODE2', 'BRAAK1_SUVR', 'BRAAK1_VOLUME', 'BRAAK34_SUVR', 'BRAAK34_VOLUME',
'META_TEMPORAL_SUVR', 'META_TEMPORAL_VOLUME', 'BRAAK56_SUVR', 'BRAAK56_VOLUME']].copy()
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [6]:
temp = pd.read_csv('../archivos_originales/pet/BAIPETNMRC.csv')
temp = temp[temp.MODALITY == 'FDG']
df2 = temp[['RID', 'VISCODE2', 'HIPPL01', 'FRTSUPL01', 'FRTMIDL01', 'PARAHIPL01', 'FUSFRML01', 'OCCMIDL01',
'ANGULL01', 'PARIINFL01', 'SUPMRGL01', 'TMPMIDL01', 'PRECUNL01', 'CINGPSTL01', 'PARAHIPR01', 'FRTSUPR01',
'OCCMIDR01', 'FUSFRMR01', 'FRTMIDR01', 'ANGULR01', 'PARIINFR01', 'TMPMIDR01', 'SUPMRGR01', 'PRCUNSR01',
'HIPPR01', 'LINGUALL01', 'LINGUALR01', 'CINGPSTR01', 'FRTINFL01', 'FRTINFR01', 'PARISUPL01', 'PARISUPR01',
'INSULAL01', 'INSULAR01', 'CINGANTL01', 'CINGANTR01', 'CINGMIDL01', 'CINGMIDR01', 'TMPSUPL01', 'TMPSUPR01',
'TMPINFL01', 'TMPINFR01', 'FRTSUPL02', 'FRTMIDL02', 'CINGPSTL02', 'CINGMIDL02', 'FRTSMEDL02', 'FUSFRML02',
'TMPMIDL02', 'OCCMIDL02', 'TMPINFL02', 'PRECUNL02', 'CINGANTL02', 'FRTMIDOR02', 'FRTMIDR02', 'FRTSUPR02',
'ANGULR02', 'ANGULL02', 'PARIINFR02', 'TMPMIDR02', 'INSULAR02', 'TMPPOSR02', 'CINGANTR02', 'CINGMIDR02',
'PRECUNR02', 'RECTUSR02', 'CINGPSTR02', 'PARIINFL02', 'INSULAL02', 'FRTINFL02', 'FRTINFR02', 'OCCMIDR02',
'FRTMIDOL02', 'FRTSMEDR02', 'FUSFMR02', 'RECTUSL02', 'TMPPOSL02', 'PARISUPL02', 'PARISUPR02', 'SUPMRGL02',
'SUPMRGR02', 'TMPINFR02', 'HCI', 'MMPLS', 'ICA', 'PCA2', 'PLSFDG01', 'HCI_2014', 'SROI']].copy()
df2 = df2.add_suffix('_FDG')
df2.rename(columns={'RID_FDG': 'RID', 'VISCODE2_FDG': 'VISCODE2'}, inplace=True)
num = df2._get_numeric_data()
num[num < 0] = None
df2['VISCODE2'] = df2['VISCODE2'].astype('str')
df2['Visit'] = df2['VISCODE2'].apply(visit)
df2.drop(columns=['VISCODE2'], inplace=True)

df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [7]:
# temp = pd.read_csv('../archivos_originales/pet/BAIPETNMRC.csv')
# temp = temp[temp.MODALITY == 'AV45']
# df2 = temp[['RID', 'VISCODE2', 'HIPPL01', 'FRTSUPL01', 'FRTMIDL01', 'PARAHIPL01', 'FUSFRML01', 'OCCMIDL01', 'ANGULL01', 'PARIINFL01', 'SUPMRGL01',
# 'TMPMIDL01', 'PRECUNL01', 'CINGPSTL01', 'PARAHIPR01', 'FRTSUPR01', 'OCCMIDR01', 'FUSFRMR01', 'FRTMIDR01', 'ANGULR01', 'PARIINFR01', 'TMPMIDR01',
# 'SUPMRGR01', 'PRCUNSR01', 'HIPPR01', 'LINGUALL01', 'LINGUALR01', 'CINGPSTR01', 'FRTINFL01', 'FRTINFR01', 'PARISUPL01', 'PARISUPR01', 'INSULAL01',
# 'INSULAR01', 'CINGANTL01', 'CINGANTR01', 'CINGMIDL01', 'CINGMIDR01', 'TMPSUPL01', 'TMPSUPR01', 'TMPINFL01', 'TMPINFR01', 'FRTSUPL02', 'FRTMIDL02',
# 'CINGPSTL02', 'CINGMIDL02', 'FRTSMEDL02', 'FUSFRML02', 'TMPMIDL02', 'OCCMIDL02', 'TMPINFL02', 'PRECUNL02', 'CINGANTL02', 'FRTMIDOR02', 'FRTMIDR02',
# 'FRTSUPR02', 'ANGULR02', 'ANGULL02', 'PARIINFR02', 'TMPMIDR02', 'INSULAR02', 'TMPPOSR02', 'CINGANTR02', 'CINGMIDR02', 'PRECUNR02', 'RECTUSR02',
# 'CINGPSTR02', 'PARIINFL02', 'INSULAL02', 'FRTINFL02', 'FRTINFR02', 'OCCMIDR02', 'FRTMIDOL02', 'FRTSMEDR02', 'FUSFMR02', 'RECTUSL02', 'TMPPOSL02',
# 'PARISUPL02', 'PARISUPR02', 'SUPMRGL02', 'SUPMRGR02', 'TMPINFR02', 'FRTMIDL03', 'FRTMIDR03', 'FRTSUPL03', 'FRTSUPR03', 'FRTSMEDL03', 'FRTSMEDR03',
# 'TMPSUPL03', 'TMPSUPR03', 'TMPMIDL03', 'TMPMIDR03', 'TMPINFL03', 'TMPINFR03', 'FUSFRML03', 'FUSFRMR03', 'LINGUALL03', 'LINGUALR03', 'PARAHIPL03',
# 'PARAHIPR03', 'PARISUPL03', 'PARISUPR03', 'PARIINFL03', 'PARIINFR03', 'PRECUNL03', 'PRECUNR03', 'CINGANT03', 'CINGMID03', 'CINGPST03', 'ANGULR03',
# 'OCCMIDL03', 'OCCMIDR03', 'OCCSUPL03', 'OCCSUPR03', 'OCCINFL03', 'OCCINFR03', 'THALAML03', 'THALAMR03', 'FRTMEDL03', 'FRTMEDR03', 'SUPMRGL03',
# 'SUPMRGR03', 'FRTMIDL04', 'FRTMIDR04', 'FRTSUPL04', 'FRTSUPR04', 'FRTSMEDL04', 'FRTSMEDR04', 'TMPSUPL04', 'TMPSUPR04', 'TMPMIDL04', 'TMPMIDR04',
# 'TMPINFL04', 'TMPINFR04', 'FUSFRML04', 'FUSFRMR04', 'LINGUALL04', 'LINGUALR04', 'PARAHIPL04', 'PARAHIPR04', 'PARISUPL04', 'PARISUPR04',
# 'PARIINFL04', 'PARIINFR04', 'PRECUNL04', 'PRECUNR04', 'CINGANT04', 'CINGMID04', 'CINGPST04', 'OCCMIDL04', 'OCCMIDR04', 'OCCSUPL04', 'OCCSUPR04',
# 'OCCINFL04', 'OCCINFR04', 'THALAML04', 'THALAMR04', 'FRTMEDL04', 'FRTMEDR04', 'SUPMRGL04', 'SUPMRGR04', 'ANGULL04', 'ANGULR04', 'FRTMIDL05',
# 'FRTMIDR05', 'FRTSUPL05', 'FRTSUPR05', 'FRTSMEDL05', 'FRTSMEDR05', 'TMPSUPL05', 'TMPSUPR05', 'TMPMIDL05', 'TMPMIDR05', 'TMPINFL05', 'TMPINFR05',
# 'FUSFRML05', 'FUSFRMR05', 'PARAHIPL05', 'PARAHIPR05', 'PARISUPL05', 'PARISUPR05', 'PARIINFL05', 'PARIINFR05', 'PRECUNL05', 'PRECUNR05',
# 'CINGANT05', 'CINGMID05', 'CINGPST05', 'OCCMIDL05', 'OCCMIDR05', 'OCCSUPL05', 'OCCSUPR05', 'OCCINFL05', 'OCCINFR05', 'THALAML05', 'THALAMR05',
# 'FRTMEDL05', 'FRTMEDR05', 'ANGULR05', 'ANGULL05', 'CALCARL05', 'CALCARR05', 'LINGUALL05', 'LINGUALR05', 'CEREB8L05', 'CEREB8R05', 'CERBCR2L05',
# 'CERBCR2R05', 'SUPMRGL05', 'SUPMRGR05', 'FRTMIDL06', 'FRTMIDR06', 'FRTSUPL06', 'FRTSUPR06', 'FRTSMEDL06', 'FRTSMEDR06', 'TMPSUPL06',
# 'TMPSUPR06', 'TMPMIDL06', 'TMPMIDR06', 'TMPINFL06', 'TMPINFR06', 'FUSFRML06', 'FUSFRMR06', 'LINGUALL06', 'LINGUALR06', 'PARAHIPL06',
# 'PARAHIPR06', 'PARISUPL06', 'PARISUPR06', 'PARIINFL06', 'PARIINFR06', 'PRECUNL06', 'PRECUNR06', 'CINGANT06', 'CINGMID06', 'CINGPST06',
# 'OCCMIDL06', 'OCCMIDR06', 'OCCSUPL06', 'OCCSUPR06', 'OCCINFL06', 'OCCINFR06', 'THALAML06', 'THALAMR06', 'FRTMEDL06', 'FRTMEDR06', 'HIPPL06',
# 'HIPPR06', 'INDGLBNDX', 'INDTEPNDX', 'PRECUNL07', 'CINGPST07', 'PARIINFR07', 'TMPMIDL07', 'CUNEUSL08', 'TMPMIDR08', 'TMPINFL09', 'CINGPST09',
# 'PRECUNL09', 'PARIINFR09', 'TMPINFL10', 'PRECUNL10', 'TMPINFL11', 'OCCMIDL11', 'CINGPST11', 'CINGMID11', 'TMPPOSR12', 'CINGPSTR12',
# 'HCI', 'MCSUVR', 'FNMPREC', 'FNAPREC', 'FNAPC', 'FEAPREC', 'FMAPREC', 'FMAPC', 'AVNEFRONT', 'AVNMFRONT', 'AVNAFRONT', 'AVEMTEMP', 'AVEATEMP',
# 'AVMAOCCIP', 'FEAPC2', 'FEMPC2', 'FMAPREC2', 'FNAPARI2', 'FNEHC2', 'FNMTEMP2', 'AVEATEMP2', 'AVEMTEMP2', 'AVMAFRNT2', 'AVNATEMP2',
# 'AVNEFRNT2', 'AVNMPREC2', 'MMPLS', 'ICA', 'PCA2', 'PLSFDG01', 'HCI001', 'MCSUVRWM', 'MCSUVRWM2', 'HCI_2014', 'SROI', 'MCSUVRCERE',
# 'MCSUVRWM3']].copy()
# df2 = df2.add_suffix('_AV45')
# df2.rename(columns={'RID_AV45': 'RID', 'VISCODE2_AV45': 'VISCODE2'}, inplace=True)
# num = df2._get_numeric_data()
# num[num < 0] = None
# df2['VISCODE2'] = df2['VISCODE2'].astype('str')
# df2['Visit'] = df2['VISCODE2'].apply(visit)
# df2.drop(columns=['VISCODE2'], inplace=True)

# df = pd.merge(df, df2, on=['RID', 'Visit'], how='outer')

In [8]:
# cols = list(df.columns)
# cols

In [9]:
df = df.sort_values(['RID', 'Visit'])
df

,RID,Visit,MEAN_METAROI_PONSVERMIS,BRAAK1_SUVR,BRAAK1_VOLUME,BRAAK34_SUVR,BRAAK34_VOLUME,META_TEMPORAL_SUVR,META_TEMPORAL_VOLUME,BRAAK56_SUVR,BRAAK56_VOLUME,HIPPL01_FDG,FRTSUPL01_FDG,FRTMIDL01_FDG,PARAHIPL01_FDG,FUSFRML01_FDG,OCCMIDL01_FDG,ANGULL01_FDG,PARIINFL01_FDG,SUPMRGL01_FDG,TMPMIDL01_FDG,PRECUNL01_FDG,CINGPSTL01_FDG,PARAHIPR01_FDG,FRTSUPR01_FDG,OCCMIDR01_FDG,FUSFRMR01_FDG,FRTMIDR01_FDG,ANGULR01_FDG,PARIINFR01_FDG,TMPMIDR01_FDG,SUPMRGR01_FDG,PRCUNSR01_FDG,HIPPR01_FDG,LINGUALL01_FDG,LINGUALR01_FDG,CINGPSTR01_FDG,FRTINFL01_FDG,FRTINFR01_FDG,PARISUPL01_FDG,PARISUPR01_FDG,INSULAL01_FDG,INSULAR01_FDG,CINGANTL01_FDG,CINGANTR01_FDG,CINGMIDL01_FDG,CINGMIDR01_FDG,TMPSUPL01_FDG,TMPSUPR01_FDG,TMPINFL01_FDG,TMPINFR01_FDG,FRTSUPL02_FDG,FRTMIDL02_FDG,CINGPSTL02_FDG,CINGMIDL02_FDG,FRTSMEDL02_FDG,FUSFRML02_FDG,TMPMIDL02_FDG,OCCMIDL02_FDG,TMPINFL02_FDG,PRECUNL02_FDG,CINGANTL02_FDG,FRTMIDOR02_FDG,FRTMIDR02_FDG,FRTSUPR02_FDG,ANGULR02_FDG,ANGULL02_FDG,PARIINFR02_FDG,TMPMIDR02_FDG,INSULAR02_FDG,TMPPOSR02_FDG,CINGANTR02_FDG,CINGMIDR02_FDG,PRECUNR02_FDG,RECTUSR02_FDG,CINGPSTR02_FDG,PARIINFL02_FDG,INSULAL02_FDG,FRTINFL02_FDG,FRTINFR02_FDG,OCCMIDR02_FDG,FRTMIDOL02_FDG,FRTSMEDR02_FDG,FUSFMR02_FDG,RECTUSL02_FDG,TMPPOSL02_FDG,PARISUPL02_FDG,PARISUPR02_FDG,SUPMRGL02_FDG,SUPMRGR02_FDG,TMPINFR02_FDG,HCI_FDG,MMPLS_FDG,ICA_FDG,PCA2_FDG,PLSFDG01_FDG,HCI_2014_FDG,SROI_FDG
1,2,0.0,1.336154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.423,189.289,176.0650,124.189,127.127,1.7672,188.702,174.004,184.003,153.133,192.0380,161.486,126.803,199.549,168.205,141.414,151.053,211.981,200.172,191.411,147.705,2.1626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,174.573,153.126,166.633,203.896,1.9076,162.655,134.658,148.7910,178.0750,120.841,192.0380,163.155,167.896,191.644,199.695,198.486,189.991,212.493,179.171,158.182,150.296,145.585,208.713,219.752,127.548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.75,NaN,NaN,NaN,NaN,11.3802,1.2033
0,2,6.0,1.222817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.57,NaN,NaN,NaN,NaN,12.9838,1.1803
5,3,0.0,1.108605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.787,196.357,1.6942,982.463,992.775,139.3470,163.597,162.897,165.885,127.776,1.7647,178.213,893.697,193.984,152.274,110.824,170.064,185.249,191.291,167.398,144.804,200.8980,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.672,144.001,160.455,201.435,195.3160,173.124,104.532,1.1576,1.3689,126.861,1.7647,176.883,185.014,188.704,196.022,174.191,149.703,183.574,149.179,139.697,131.732,172.644,204.912,203.544,159.249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.51,NaN,NaN,NaN,NaN,212.0660,1.1339
2,3,6.0,1.077957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.82,NaN,NaN,NaN,NaN,247.5930,1.1080
3,3,12.0,1.116258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.43,NaN,NaN,NaN,NaN,231.9850,1.1217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4847,7021,NaN,NaN,2.0625,3246.0,1.7562,104522.0,2.0870,57523.0,1.2050,305170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4848,7023,0.0,NaN,1.1736,3247.0,1.0785,120188.0,1.1217,64597.0,1.0001,337331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4849,7024,0.0,NaN,1.1951,2865.0,1.1269,130728.0,1.1793,72709.0,0.9826,367707.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4850,7029,0.0,NaN,0.9117,3351.0,0.9290,116205.0,0.9623,64523.0,0.8596,318229.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4851,7033,0.0,NaN,2.0830,3198.0,2.3089,98762.0,2.6712,55933.0,1.8377,277045.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
empty_columns = []
for i in range(len(df.columns)):
    cont = 0
    for j in range(len(df)):
        if pd.isna(df[df.columns[i]][j]):
            cont += 1
    if cont == len(df):
        print(f'Numero de nans en {df.columns[i]}: {cont}')
        empty_columns.append(df.columns[i])

Numero de nans en HIPPR01_FDG: 4855
Numero de nans en LINGUALL01_FDG: 4855
Numero de nans en LINGUALR01_FDG: 4855
Numero de nans en CINGPSTR01_FDG: 4855
Numero de nans en FRTINFL01_FDG: 4855
Numero de nans en FRTINFR01_FDG: 4855
Numero de nans en PARISUPL01_FDG: 4855
Numero de nans en PARISUPR01_FDG: 4855
Numero de nans en INSULAL01_FDG: 4855
Numero de nans en INSULAR01_FDG: 4855
Numero de nans en CINGANTL01_FDG: 4855
Numero de nans en CINGANTR01_FDG: 4855
Numero de nans en CINGMIDL01_FDG: 4855
Numero de nans en CINGMIDR01_FDG: 4855
Numero de nans en TMPSUPL01_FDG: 4855
Numero de nans en TMPSUPR01_FDG: 4855
Numero de nans en TMPINFL01_FDG: 4855
Numero de nans en CINGPSTR02_FDG: 4855
Numero de nans en PARIINFL02_FDG: 4855
Numero de nans en INSULAL02_FDG: 4855
Numero de nans en FRTINFL02_FDG: 4855
Numero de nans en FRTINFR02_FDG: 4855
Numero de nans en OCCMIDR02_FDG: 4855
Numero de nans en FRTMIDOL02_FDG: 4855
Numero de nans en FRTSMEDR02_FDG: 4855
Numero de nans en FUSFMR02_FDG: 4855
Numero de nans en RECTUSL02_FDG: 4855
Numero de nans en TMPPOSL02_FDG: 4855
Numero de nans en PARISUPL02_FDG: 4855
Numero de nans en PARISUPR02_FDG: 4855
Numero de nans en SUPMRGL02_FDG: 4855
Numero de nans en SUPMRGR02_FDG: 4855
Numero de nans en TMPINFR02_FDG: 4855
Numero de nans en ICA_FDG: 4855

In [11]:
len(empty_columns)

34

In [12]:
df.drop(empty_columns, axis=1, inplace=True)
df

,RID,Visit,MEAN_METAROI_PONSVERMIS,BRAAK1_SUVR,BRAAK1_VOLUME,BRAAK34_SUVR,BRAAK34_VOLUME,META_TEMPORAL_SUVR,META_TEMPORAL_VOLUME,BRAAK56_SUVR,BRAAK56_VOLUME,HIPPL01_FDG,FRTSUPL01_FDG,FRTMIDL01_FDG,PARAHIPL01_FDG,FUSFRML01_FDG,OCCMIDL01_FDG,ANGULL01_FDG,PARIINFL01_FDG,SUPMRGL01_FDG,TMPMIDL01_FDG,PRECUNL01_FDG,CINGPSTL01_FDG,PARAHIPR01_FDG,FRTSUPR01_FDG,OCCMIDR01_FDG,FUSFRMR01_FDG,FRTMIDR01_FDG,ANGULR01_FDG,PARIINFR01_FDG,TMPMIDR01_FDG,SUPMRGR01_FDG,PRCUNSR01_FDG,TMPINFR01_FDG,FRTSUPL02_FDG,FRTMIDL02_FDG,CINGPSTL02_FDG,CINGMIDL02_FDG,FRTSMEDL02_FDG,FUSFRML02_FDG,TMPMIDL02_FDG,OCCMIDL02_FDG,TMPINFL02_FDG,PRECUNL02_FDG,CINGANTL02_FDG,FRTMIDOR02_FDG,FRTMIDR02_FDG,FRTSUPR02_FDG,ANGULR02_FDG,ANGULL02_FDG,PARIINFR02_FDG,TMPMIDR02_FDG,INSULAR02_FDG,TMPPOSR02_FDG,CINGANTR02_FDG,CINGMIDR02_FDG,PRECUNR02_FDG,RECTUSR02_FDG,HCI_FDG,MMPLS_FDG,PCA2_FDG,PLSFDG01_FDG,HCI_2014_FDG,SROI_FDG
1,2,0.0,1.336154,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.423,189.289,176.0650,124.189,127.127,1.7672,188.702,174.004,184.003,153.133,192.0380,161.486,126.803,199.549,168.205,141.414,151.053,211.981,200.172,191.411,147.705,2.1626,174.573,153.126,166.633,203.896,1.9076,162.655,134.658,148.7910,178.0750,120.841,192.0380,163.155,167.896,191.644,199.695,198.486,189.991,212.493,179.171,158.182,150.296,145.585,208.713,219.752,127.548,4.75,NaN,NaN,NaN,11.3802,1.2033
0,2,6.0,1.222817,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.57,NaN,NaN,NaN,12.9838,1.1803
5,3,0.0,1.108605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,960.787,196.357,1.6942,982.463,992.775,139.3470,163.597,162.897,165.885,127.776,1.7647,178.213,893.697,193.984,152.274,110.824,170.064,185.249,191.291,167.398,144.804,200.8980,164.672,144.001,160.455,201.435,195.3160,173.124,104.532,1.1576,1.3689,126.861,1.7647,176.883,185.014,188.704,196.022,174.191,149.703,183.574,149.179,139.697,131.732,172.644,204.912,203.544,159.249,9.51,NaN,NaN,NaN,212.0660,1.1339
2,3,6.0,1.077957,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.82,NaN,NaN,NaN,247.5930,1.1080
3,3,12.0,1.116258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.43,NaN,NaN,NaN,231.9850,1.1217
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4847,7021,NaN,NaN,2.0625,3246.0,1.7562,104522.0,2.0870,57523.0,1.2050,305170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4848,7023,0.0,NaN,1.1736,3247.0,1.0785,120188.0,1.1217,64597.0,1.0001,337331.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4849,7024,0.0,NaN,1.1951,2865.0,1.1269,130728.0,1.1793,72709.0,0.9826,367707.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4850,7029,0.0,NaN,0.9117,3351.0,0.9290,116205.0,0.9623,64523.0,0.8596,318229.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4851,7033,0.0,NaN,2.0830,3198.0,2.3089,98762.0,2.6712,55933.0,1.8377,277045.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.to_csv('pet.csv', index=False)