In [26]:
import pandas as pd
pd.set_option('display.max_rows', 500)

In [41]:
mapping = {
  "APOE_A1": "1",
  "APOE_A2": "2",
  "APOE": "3",
  "TOMM40_A1": "4",
  "TOMM40_A2": "5",
  "PHS": "6",
  "CIR": "7",
  "EUR_AB42": "8",
  "EUR_AB42/40": "9",
  "FUJI_AB42": "10",
  "FUJI_AB42/40": "11",
  "UGOT_PLASMAPTAU": "12",
  "TS_RATIO": "13",
  "TS_RATIO_ADJ": "14",
  "TL": "15",
  "BACE": "16",
  "APP": "17",
  "UPK_AB42": "18",
  "UPK_TAU": "19",
  "UPK_PTAU": "20",
  "UPKelec_AB42": "21",
  "UPKelec_TAU": "22",
  "UPKelec_PTAU": "23",
  "UPplasma_AB42": "24",
  "MEAN_METAROI_PONSVERMIS": "25",
  "BRAAK1_SUVR": "26",
  "BRAAK34_SUVR": "27",
  "BRAAK56_SUVR": "28",
  "CEREBELLUMGREYMATTER_AV45": "29",
  "WHOLECEREBELLUM_AV45": "30",
  "FRONTAL_AV45": "31",
  "CINGULATE_AV45": "32",
  "PARIETAL_AV45": "33",
  "TEMPORAL_AV45": "34",
  "COMPOSITE_AV45": "35",
  "SUMMARYSUVR_WHOLECEREBNORM_AV45": "36",
  "SUMMARYSUVR_COMPOSITE_REFNORM_AV45": "37",
  "LH_CAUDALANTERIORCINGULATE_AV45": "38",
  "LH_CAUDALMIDDLEFRONTAL_AV45": "39",
  "LH_CUNEUS_AV45": "40",
  "LH_ENTORHINAL_AV45": "41",
  "LH_FRONTALPOLE_AV45": "42",
  "LH_FUSIFORM_AV45": "43",
  "LH_INFERIORPARIETAL_AV45": "44",
  "LH_INFERIORTEMPORAL_AV45": "45",
  "LH_INSULA_AV45": "46",
  "LH_ISTHMUSCINGULATE_AV45": "47",
  "LH_LATERALOCCIPITAL_AV45": "48",
  "LH_LATERALORBITOFRONTAL_AV45": "49",
  "LH_LINGUAL_AV45": "50",
  "LH_MEDIALORBITOFRONTAL_AV45": "51",
  "LH_MIDDLETEMPORAL_AV45": "52",
  "LH_PARACENTRAL_AV45": "53",
  "LH_PARAHIPPOCAMPAL_AV45": "54",
  "LH_PARSOPERCULARIS_AV45": "55",
  "LH_PARSORBITALIS_AV45": "56",
  "LH_PARSTRIANGULARIS_AV45": "57",
  "LH_POSTCENTRAL_AV45": "58",
  "LH_POSTERIORCINGULATE_AV45": "59",
  "LH_PRECENTRAL_AV45": "60",
  "LH_PRECUNEUS_AV45": "61",
  "LH_ROSTRALANTERIORCINGULATE_AV45": "62",
  "LH_ROSTRALMIDDLEFRONTAL_AV45": "63",
  "LH_SUPERIORFRONTAL_AV45": "64",
  "LH_SUPERIORPARIETAL_AV45": "65",
  "LH_SUPERIORTEMPORAL_AV45": "66",
  "LH_SUPRAMARGINAL_AV45": "67",
  "LH_TEMPORALPOLE_AV45": "68",
  "LH_TRANSVERSETEMPORAL_AV45": "69",
  "RH_CAUDALANTERIORCINGULATE_AV45": "70",
  "RH_CAUDALMIDDLEFRONTAL_AV45": "71",
  "RH_CUNEUS_AV45": "72",
  "RH_ENTORHINAL_AV45": "73",
  "RH_FRONTALPOLE_AV45": "74",
  "RH_FUSIFORM_AV45": "75",
  "RH_INFERIORPARIETAL_AV45": "76",
  "RH_INFERIORTEMPORAL_AV45": "77",
  "RH_INSULA_AV45": "78",
  "RH_ISTHMUSCINGULATE_AV45": "79",
  "RH_LATERALOCCIPITAL_AV45": "80",
  "RH_LATERALORBITOFRONTAL_AV45": "81",
  "RH_LINGUAL_AV45": "82",
  "RH_MEDIALORBITOFRONTAL_AV45": "83",
  "RH_MIDDLETEMPORAL_AV45": "84",
  "RH_PARACENTRAL_AV45": "85",
  "RH_PARAHIPPOCAMPAL_AV45": "86",
  "RH_PARSOPERCULARIS_AV45": "87",
  "RH_PARSORBITALIS_AV45": "88",
  "RH_PARSTRIANGULARIS_AV45": "89",
  "RH_POSTCENTRAL_AV45": "90",
  "RH_POSTERIORCINGULATE_AV45": "91",
  "RH_PRECENTRAL_AV45": "92",
  "RH_PRECUNEUS_AV45": "93",
  "RH_ROSTRALANTERIORCINGULATE_AV45": "94",
  "RH_ROSTRALMIDDLEFRONTAL_AV45": "95",
  "RH_SUPERIORFRONTAL_AV45": "96",
  "RH_SUPERIORPARIETAL_AV45": "97",
  "RH_SUPERIORTEMPORAL_AV45": "98",
  "RH_SUPRAMARGINAL_AV45": "99",
  "RH_TEMPORALPOLE_AV45": "100",
  "RH_TRANSVERSETEMPORAL_AV45": "101",
  "ANGULL_FDG": "102",
  "ANGULR_FDG": "103",
  "ANGULR02_FDG": "104",
  "ANGULL02_FDG": "105",
  "ANGULR03_FDG": "106",
  "ANGULR04_FDG": "107",
  "ANGULR05_FDG": "108",
  "CINGPSTL_FDG": "109",
  "CINGPSTL02_FDG": "110",
  "CINGPST_FDG": "111",
  "CINGPST04_FDG": "112",
  "CINGPST05_FDG": "113",
  "CINGPST07_FDG": "114",
  "CINGPST09_FDG": "115",
  "CINGPSTR_FDG": "116",
  "TMPINFR_FDG": "117",
  "TMPINFL_FDG": "118",
  "TMPINFL03_FDG": "119",
  "TMPINFR03_FDG": "120",
  "TMPINFL04_FDG": "121",
  "TMPINFR04_FDG": "122",
  "TMPINFR05_FDG": "123",
  "TMPINFL06_FDG": "124",
  "TMPINFR06_FDG": "125",
  "TMPINFL09_FDG": "126",
  "TMPINFL10_FDG": "127",
  "TMPINFL11_FDG": "128",
  "HCI_FDG": "129",
  "HCI_2014_FDG": "130",
  "CEREB_TCV": "131",
  "CEREB_TCB": "132",
  "CEREB_TCC": "133",
  "CEREB_GRAY": "134",
  "CEREB_WHITE": "135",
  "L_HIPPO": "136",
  "R_HIPPO": "137",
  "TBM_1": "138",
  "TBM_2": "139",
  "IPCA": "140",
  "LHIPPO": "141",
  "RHIPPO": "142",
  "ST103CV": "143",
  "ST111CV": "144",
  "ST115CV": "145",
  "ST116CV": "146",
  "ST118CV": "147",
  "ST119CV": "148",
  "ST12SV": "149",
  "ST24CV": "150",
  "ST26CV": "151",
  "ST29SV": "152",
  "ST31CV": "153",
  "ST32CV": "154",
  "ST35CV": "155",
  "ST40CV": "156",
  "ST44CV": "157",
  "ST52CV": "158",
  "ST55CV": "159",
  "ST56CV": "160",
  "ST57CV": "161",
  "ST59CV": "162",
  "ST60CV": "163",
  "ST71SV": "164",
  "ST74CV": "165",
  "ST83CV": "166",
  "ST85CV": "167",
  "ST88SV": "168",
  "ST90CV": "169",
  "ST91CV": "170",
  "ST94CV": "171",
  "ST99CV": "172",
  "AXNAUSEA": "173",
  "AXVOMIT": "174",
  "AXDIARRH": "175",
  "AXCONSTP": "176",
  "AXABDOMN": "177",
  "AXSWEATN": "178",
  "AXDIZZY": "179",
  "AXENERGY": "180",
  "AXDROWSY": "181",
  "AXVISION": "182",
  "AXHDACHE": "183",
  "AXDRYMTH": "184",
  "AXBREATH": "185",
  "AXCOUGH": "186",
  "AXPALPIT": "187",
  "AXCHEST": "188",
  "AXURNDIS": "189",
  "AXURNFRQ": "190",
  "AXANKLE": "191",
  "AXMUSCLE": "192",
  "AXRASH": "193",
  "AXINSOMN": "194",
  "AXDPMOOD": "195",
  "AXCRYING": "196",
  "AXELMOOD": "197",
  "AXWANDER": "198",
  "AXFALL": "199",
  "HMONSET": "200",
  "HMSTEPWS": "201",
  "HMSOMATC": "202",
  "HMEMOTIO": "203",
  "HMHYPERT": "204",
  "HMSTROKE": "205",
  "HMNEURSM": "206",
  "HMNEURSG": "207",
  "HMSCORE": "208",
  "PTGENDER": "209",
  "PTDOBYY": "210",
  "PTHAND": "211",
  "PTMARRY": "212",
  "PTEDUCAT": "213",
  "GDS": "214",
  "MHPSYCH": "215",
  "MH2NEURL": "216",
  "MH3HEAD": "217",
  "MH4CARD": "218",
  "MH5RESP": "219",
  "MH6HEPAT": "220",
  "MH7DERM": "221",
  "MH8MUSCL": "222",
  "MH9ENDO": "223",
  "MH10GAST": "224",
  "MH11HEMA": "225",
  "MH12RENA": "226",
  "MH13ALLE": "227",
  "MH14ALCH": "228",
  "MH15DRUG": "229",
  "MH16SMOK": "230",
  "MH17MALI": "231",
  "MH18SURG": "232",
  "MMSE": "233",
  "MOCA": "234",
  "CDR": "235",
  "ADSP_DX": "236",
  "ADSP_MEM": "237",
  "ADSP_EXF": "238",
  "ADSP_LAN": "239",
  "ADSP_VSP": "240",
  "ADAS11": "241",
  "ADAS13": "242",
  "UW_MEM": "243",
  "UW_EF": "244"
}
for key, value in mapping.items():
    mapping[key] = int(value)

In [ ]:
# Genetic
df = pd.read_csv("description_genetic.csv", names=["Node", "Description"], header=None)
df["Number"] = df["Node"].map(mapping)
df = df[["Number", "Node", "Description"]]
df.sort_values(by=["Number"], inplace=True)
df.to_csv("description_genetic_tolatex.csv", index=False)
df

   Number       Node                                        Description
0       1    APOE_A1  Copy 1 of $APOE$ gene. The numbers correspond ...
1       2    APOE_A2                              Copy 2 of $APOE$ gene
2       3       APOE  Corresponds to both alleles together: 0 (no E4...
3       4  TOMM40_A1  Allele 1 of Translocase of Outer Mitochondria ...
4       5  TOMM40_A2  Allele 2 of Translocase of Outer Mitochondria ...
5       6        PHS                             Polygenic Hazard Score
6       7        CIR                         Cummulative Incidence Rate

In [18]:
# Molecular
df = pd.read_csv("description_molecular.csv", names=["Node", "Description"], header=None)
df.loc[df.Node == "UGOT_plasma_PTAU", "Node"] = "UGOT_PLASMAPTAU"
df["Number"] = df["Node"].map(mapping)
df = df[["Number", "Node", "Description"]]
df.sort_values(by=["Number"], inplace=True)
df.to_csv("description_molecular_tolatex.csv", index=False)
df

    Number             Node                                        Description
2        8         EUR_AB42          CSF $beta$-Amyloid 1-42 pg/mL - EUROIMMUN
3        9      EUR_AB42/40    CSF $beta$-Amyloid 1-42, 1-40 Ratio - EUROIMMUN
4       10        FUJI_AB42          CSF $beta$-amyloid 1-42 pg/mL - FUJIREBIO
5       11     FUJI_AB42/40    CSF $beta$-amyloid 1-42, 1-40 Ratio - FUJIREBIO
13      12  UGOT_PLASMAPTAU  phosphorylated tau longitudinal plasma pg/ml -...
15      13         TS_RATIO  TL/SCG Telomere length/single copy gene ratio ...
14      15               TL                    Telomere Length L in base pairs
1       16             BACE  CSF Beta Secretase pM - Biomarkers Consortium ...
0       17              APP  CSF (Cerebrospinal Fluid) Amyloid Precursor Pr...
6       18         UPK_AB42                         CSF $beta$-amyloid - UPENN
8       19          UPK_TAU                              CSF Total Tau - UPENN
7       20         UPK_PTAU                     CSF phosphorylated-tau - UPENN
9       21     UPKelec_AB42  CSF $beta$-amyloid using the fully automated R...
11      22      UPKelec_TAU  CSF Total Tau using the fully automated Roche ...
10      23     UPKelec_PTAU  CSF phosphorylated-tau using the fully automat...
12      24    UPplasma_AB42           Plasma $beta$-Amyloid 1-42 pg/mL - UPENN

In [46]:
# PET
df = pd.read_csv("description_pet.csv", names=["Node", "Description"], header=None)
df["Number"] = df["Node"].map(mapping)
df.dropna(inplace=True)
df["Number"] = df["Number"].astype(int)
df = df[["Number", "Node", "Description"]]
df.sort_values(by=["Number"], inplace=True)
df.to_csv("description_pet_tolatex.csv", index=False)
df

,Number,Node,Description
115,25,MEAN_METAROI_PONSVERMIS,Glucose metabolism normalized to pons-vermis m...
112,26,BRAAK1_SUVR,Weighted AV1451 mean of Braak region I (AV1451...
113,27,BRAAK34_SUVR,Weighted AV1451 mean of Braak region III and I...
114,28,BRAAK56_SUVR,Weighted AV1451 mean of Braak region V and VI ...
103,29,CEREBELLUMGREYMATTER_AV45,Reference region - AV45 mean of cerebellar gre...
104,30,WHOLECEREBELLUM_AV45,Reference region - AV45 mean of whole cerebell...
105,31,FRONTAL_AV45,Weighted AV45 mean in frontal regions - UC Ber...
106,32,CINGULATE_AV45,Weighted AV45 mean in anterior/posterior cingu...
107,33,PARIETAL_AV45,Weighted AV45 mean in lateral parietal regions...
108,34,TEMPORAL_AV45,Weighted AV45 mean in lateral temporal regions...
109,35,COMPOSITE_AV45,"Weighted AV45 mean in frontal, cingulate, pari..."
110,36,SUMMARYSUVR_WHOLECEREBNORM_AV45,Summary AV45 cortical SUVR normalized by whole...
111,37,SUMMARYSUVR_COMPOSITE_REFNORM_AV45,Summary AV45 cortical SUVR normalized by compo...
39,38,LH_CAUDALANTERIORCINGULATE_AV45,SUVr for AV45 in caudal anterior cingulate reg...
41,39,LH_CAUDALMIDDLEFRONTAL_AV45,SUVr for AV45 in caudal middle frontal region ...
43,40,LH_CUNEUS_AV45,SUVr for AV45 in cuneus region of the left hem...
45,41,LH_ENTORHINAL_AV45,SUVr for AV45 in entorhinal region of the left...
47,42,LH_FRONTALPOLE_AV45,SUVr for AV45 in frontal pole region of the le...
49,43,LH_FUSIFORM_AV45,SUVr for AV45 in frontal pole region of the le...
51,44,LH_INFERIORPARIETAL_AV45,SUVr for AV45 in inferior parietal region of t...
53,45,LH_INFERIORTEMPORAL_AV45,SUVr for AV45 in inferior temporal region of t...
55,46,LH_INSULA_AV45,SUVr for AV45 in insula region of the left hem...
57,47,LH_ISTHMUSCINGULATE_AV45,SUVr for AV45 in isthmus cingulate region of t...
59,48,LH_LATERALOCCIPITAL_AV45,SUVr for AV45 in lateral occipital region of t...
61,49,LH_LATERALORBITOFRONTAL_AV45,SUVr for AV45 in lateral orbitofrontal region ...
63,50,LH_LINGUAL_AV45,SUVr for AV45 in lingual region of the left he...
65,51,LH_MEDIALORBITOFRONTAL_AV45,SUVr for AV45 in medial orbitofrontal region o...
67,52,LH_MIDDLETEMPORAL_AV45,SUVr for AV45 in middle temporal region of the...
69,53,LH_PARACENTRAL_AV45,SUVr for AV45 in paracentral region of the lef...
71,54,LH_PARAHIPPOCAMPAL_AV45,SUVr for AV45 in parahippocampal region of the...
73,55,LH_PARSOPERCULARIS_AV45,SUVr for AV45 in pars opercularis region of th...
75,56,LH_PARSORBITALIS_AV45,SUVr for AV45 in pars orbitalis region of the ...
77,57,LH_PARSTRIANGULARIS_AV45,SUVr for AV45 in pars triangularis region of t...
79,58,LH_POSTCENTRAL_AV45,SUVr for AV45 in postcentral region of the lef...
81,59,LH_POSTERIORCINGULATE_AV45,SUVr for AV45 in posterior cingulate region of...
83,60,LH_PRECENTRAL_AV45,SUVr for AV45 in precentral region of the left...
85,61,LH_PRECUNEUS_AV45,SUVr for AV45 in precuneus region of the left ...
87,62,LH_ROSTRALANTERIORCINGULATE_AV45,SUVr for AV45 in rostral anterior cingulate re...
89,63,LH_ROSTRALMIDDLEFRONTAL_AV45,SUVr for AV45 in rostral middle frontal region...
91,64,LH_SUPERIORFRONTAL_AV45,SUVr for AV45 in superior frontal region of th...
93,65,LH_SUPERIORPARIETAL_AV45,SUVr for AV45 in superior parietal region of t...
95,66,LH_SUPERIORTEMPORAL_AV45,SUVr for AV45 in superior temporal region of t...
97,67,LH_SUPRAMARGINAL_AV45,SUVr for AV45 in supramarginal region of the l...
99,68,LH_TEMPORALPOLE_AV45,SUVr for AV45 in temporal pole region of the l...
101,69,LH_TRANSVERSETEMPORAL_AV45,SUVr for AV45 in transverse temporal region of...
40,70,RH_CAUDALANTERIORCINGULATE_AV45,SUVr for AV45 in caudal anterior cingulate reg...
42,71,RH_CAUDALMIDDLEFRONTAL_AV45,SUVr for AV45 in caudal middle frontal region ...
44,72,RH_CUNEUS_AV45,SUVr for AV45 in cuneus region of the right he...
46,73,RH_ENTORHINAL_AV45,SUVr for AV45 in entorhinal region of the righ...
48,74,RH_FRONTALPOLE_AV45,SUVr for AV45 in frontal pole region of the ri...
50,75,RH_FUSIFORM_AV45,SUVr for AV45 in frontal pole region of the ri...
52,76,RH_INFERIORPARIETAL_AV45,SUVr for AV45 in inferior parietal region of t...
54,77,RH_INFERIORTEMPORAL_AV45,SUVr for AV45 in inferior temporal region of t...
56,78,RH_INSULA_AV45,SUVr for AV45 in insula region of the right he...
58,79,RH_ISTHMUSCINGULATE_AV45,SUVr for AV45 in isthmus cingulate region of t...
60,80,RH_LATERALOCCIPITAL_AV45,SUVr for AV45 in lateral occipital region of t...
62,81,RH_LATERALORBITOFRONTAL_AV45,SUVr for AV45 in lateral orbitofrontal region ...
64,82,RH_LINGUAL_AV45,SUVr for AV45 in lingual region of the right h...
66,83,RH_MEDIALORBITOFRONTAL_AV45,SUVr for AV45 in medial orbitofrontal region o...
68,84,RH_MIDDLETEMPORAL_AV45,SUVr for AV45 in middle temporal region of the...
70,85,RH_PARACENTRAL_AV45,SUVr for AV45 in paracentral region of the rig...
72,86,RH_PARAHIPPOCAMPAL_AV45,SUVr for AV45 in parahippocampal region of the...
74,87,RH_PARSOPERCULARIS_AV45,SUVr for AV45 in pars opercularis region of th...
76,88,RH_PARSORBITALIS_AV45,SUVr for AV45 in pars orbitalis region of the ...
78,89,RH_PARSTRIANGULARIS_AV45,SUVr for AV45 in pars triangularis region of t...
80,90,RH_POSTCENTRAL_AV45,SUVr for AV45 in postcentral region of the rig...
82,91,RH_POSTERIORCINGULATE_AV45,SUVr for AV45 in posterior cingulate region of...
84,92,RH_PRECENTRAL_AV45,SUVr for AV45 in precentral region of the righ...
86,93,RH_PRECUNEUS_AV45,SUVr for AV45 in precuneus region of the right...
88,94,RH_ROSTRALANTERIORCINGULATE_AV45,SUVr for AV45 in rostral anterior cingulate re...
90,95,RH_ROSTRALMIDDLEFRONTAL_AV45,SUVr for AV45 in rostral middle frontal region...
92,96,RH_SUPERIORFRONTAL_AV45,SUVr for AV45 in superior frontal region of th...
94,97,RH_SUPERIORPARIETAL_AV45,SUVr for AV45 in superior parietal region of t...
96,98,RH_SUPERIORTEMPORAL_AV45,SUVr for AV45 in superior temporal region of t...
98,99,RH_SUPRAMARGINAL_AV45,SUVr for AV45 in supramarginal region of the r...
100,100,RH_TEMPORALPOLE_AV45,SUVr for AV45 in temporal pole region of the r...
102,101,RH_TRANSVERSETEMPORAL_AV45,SUVr for AV45 in transverse temporal region of...
13,102,ANGULL_FDG,Globally normalized CMRgl from Angular L - BAI...
14,103,ANGULR_FDG,Globally normalized CMRgl from Angular R - BAI...
21,109,CINGPSTL_FDG,Globally normalized CMRgl from Cingulum Post L...
22,116,CINGPSTR_FDG,Globally normalized CMRgl from Cingulum Post R...
32,117,TMPINFR_FDG,Globally normalized CMRgl from Temporal Inf R ...
33,118,TMPINFL_FDG,Globally normalized CMRgl from Temporal Inf L ...
0,129,HCI_FDG,Hypometabolic Convergence Index FDG - BAINMRC
1,130,HCI_2014_FDG,Hypometabolic Convergence Index FDG - BAINMRC

In [37]:
# MRI
df = pd.read_csv("description_mri.csv", names=["Node", "Description"], header=None)
df["Node"] = df["Node"].str.replace(r"_CV$", "CV", regex=True)
df["Node"] = df["Node"].str.replace(r"_SV$", "SV", regex=True)
df["Number"] = df["Node"].map(mapping)
df.dropna(inplace=True)
df["Number"] = df["Number"].astype(int)
df = df[["Number", "Node", "Description"]]
df.sort_values(by=["Number"], inplace=True)
df.to_csv("description_mri_tolatex.csv", index=False)
df

    Number         Node                                        Description
0      131    CEREB_TCV  Total Cerebrum Cranial Volume (supratentorial ...
1      132    CEREB_TCB         Total Cerebrum Brain Volume (cm$^3$) - WMH
2      133    CEREB_TCC  Total Cerebrum Cerebrospinal Fluid Volume (cm$...
3      134   CEREB_GRAY   Total Cerebrum Gray Matter Volume (cm$^3$) - WMH
4      135  CEREB_WHITE  Total Cerebrum White Matter Volume (cm$^3$) - WMH
5      136      L_HIPPO   Segmented Left Hippocampus Volume (cm$^3$) - WMH
6      137      R_HIPPO  Segmented Right Hippocampus Volume (cm$^3$) - WMH
11     138        TBM_1  Measure 1  - Numerical summary of cumulative t...
12     139        TBM_2  Measure 2  - Numerical summary of cumulative t...
13     140         IPCA  Percent annualized whole brain atrophy detecte...
14     141       LHIPPO  Left Hippocampus Volume (mm$^3$) Semi-automate...
15     142       RHIPPO  Right Hippocampus Volume (mm$^3$) Semi-automat...
40     143      ST103CV  Cortical Volume of Right Parahippocampal (mm$^...
41     144      ST111CV  Cortical Volume of Right Precuneus (mm$^3$) Cr...
42     145      ST115CV  Cortical Volume of Right Superior Frontal (mm$...
43     146      ST116CV  Cortical Volume of Right Superior Parietal (mm...
44     147      ST118CV  Cortical Volume of Right Supramarginal (mm$^3$...
45     148      ST119CV  Cortical Volume of Right Temporal Pole (mm$^3$...
16     149       ST12SV  Subcortical Volume of Left Amygdala (mm$^3$) C...
17     150       ST24CV  Cortical Volume of Left Entorhinal (mm$^3$) Cr...
18     151       ST26CV  Cortical Volume of Left Fusiform (mm$^3$) Cros...
19     152       ST29SV  Subcortical Volume of Left Hippocampus (mm$^3$...
20     153       ST31CV  Cortical Volume of Left Inferior Parietal (mm$...
21     154       ST32CV  Cortical Volume of Left Inferior Temporal (mm$...
22     155       ST35CV  Cortical Volume of Left Lateral Occipital (mm$...
24     156       ST40CV  Cortical Volume of Left Middle Temporal (mm$^3...
23     157       ST44CV  Cortical Volume of Left Parahippocampal (mm$^3...
25     158       ST52CV  Cortical Volume of Left Precuneus (mm$^3$) Cro...
26     159       ST55CV  Cortical Volume of Left Rostral Middle Frontal...
27     160       ST56CV  Cortical Volume of Left Superior Frontal (mm$^...
28     161       ST57CV  Cortical Volume of Left Superior Parietal (mm$...
29     162       ST59CV  Cortical Volume of Left Supramarginal (mm$^3$)...
30     163       ST60CV  Cortical Volume of Left Temporal Pole (mm$^3$)...
31     164       ST71SV  Subcortical Volume of Right Amygdala (mm$^3$) ...
32     165       ST74CV  Cortical Volume of Right Caudal Middle Frontal...
33     166       ST83CV  Cortical Volume of Right Entorhinal (mm$^3$) C...
34     167       ST85CV  Cortical Volume of Right Fusiform (mm$^3$) Cro...
35     168       ST88SV  Subcortical Volume of Right Hippocampus (mm$^3...
36     169       ST90CV  Cortical Volume of Right Inferior Parietal (mm...
37     170       ST91CV  Cortical Volume of Right Inferior Temporal (mm...
38     171       ST94CV  Cortical Volume of Right Lateral Occipital (mm...
39     172       ST99CV  Cortical Volume of Right Middle Temporal (mm$^...

In [ ]:
# Phenotype
df = pd.read_csv("description_phenotype.csv", names=["Node", "Description"], header=None)
df["Number"] = df["Node"].map(mapping)
df = df[["Number", "Node", "Description"]]
df.sort_values(by=["Number"], inplace=True)
df.to_csv("description_phenotype_tolatex.csv", index=False)
df

    Number      Node                                        Description
9      233      MMSE  Mini Mental State Examination, paper-based tes...
8      234      MOCA                 Montreal Cognitive Assessment test
7      235       CDR  Clinical Dementia Rate (Normal: 0, Very Slight...
0      236   ADSP_DX                          Clinical Diagnosis - ADSP
2      237  ADSP_MEM           Harmonized Composite Memory Score - ADSP
1      238  ADSP_EXF  Harmonized Composite Executive Function Score ...
3      239  ADSP_LAN         Harmonized Composite Language Score - ADSP
4      240  ADSP_VSP     Harmonized Composite Visuospatial Score - ADSP
5      241    ADAS11  Alzheimer’s Disease Assessment Scale Total sco...
6      242    ADAS13  Alzheimer’s Disease Assessment Scale Total sco...
11     243    UW_MEM                        Composite Memory Score - UW
10     244     UW_EF         Composite Executive Functioning Score - UW

In [ ]:
# Risk factors
df = pd.read_csv("description_riskfactors.csv", names=["Node", "Description"], header=None)
df["Number"] = df["Node"].map(mapping)
df = df[["Number", "Node", "Description"]]
df.sort_values(by=["Number"], inplace=True)
df.to_csv("description_riskfactors_tolatex.csv", index=False)
df

    Number      Node                                        Description
33     173  AXNAUSEA                                      Nausea - ADSX
34     174   AXVOMIT                                    Vomiting - ADSX
35     175  AXDIARRH                                    Diarrhea - ADSX
36     176  AXCONSTP                                Constipation - ADSX
37     177  AXABDOMN                              Abdominal Pain - ADSX
38     178  AXSWEATN                                    Sweating - ADSX
39     179   AXDIZZY                                   Dizziness - ADSX
40     180  AXENERGY                                  Low energy - ADSX
41     181  AXDROWSY                                  Drowsiness - ADSX
42     182  AXVISION                              Blurred vision - ADSX
43     183  AXHDACHE                                    Headache - ADSX
44     184  AXDRYMTH                                   Dry Mouth - ADSX
45     185  AXBREATH                          Shortage Of Breath - ADSX
46     186   AXCOUGH                                    Coughing - ADSX
47     187  AXPALPIT                                Palpitations - ADSX
48     188   AXCHEST                                  Chest pain - ADSX
49     189  AXURNDIS          Urinary discomfort (e.g., burning) - ADSX
50     190  AXURNFRQ                           Urinary frequency - ADSX
51     191   AXANKLE                              Ankle swelling - ADSX
52     192  AXMUSCLE                         Muscloskeletal Pain - ADSX
53     193    AXRASH                                        Rash - ADSX
54     194  AXINSOMN                                    Insomnia - ADSX
55     195  AXDPMOOD                             Depressive Mood - ADSX
56     196  AXCRYING                                      Crying - ADSX
57     197  AXELMOOD                               Elevated Mood - ADSX
58     198  AXWANDER                                   Wandering - ADSX
59     199    AXFALL                                        Fall - ADSX
24     200   HMONSET         Abrupt Onset Dementia - Modified Hachinski
25     201  HMSTEPWS  Stepwise Deterioration Of Dementia - Modified ...
26     202  HMSOMATC            Somatic Complaints - Modified Hachinski
27     203  HMEMOTIO        Emotional Incontinence - Modified Hachinski
28     204  HMHYPERT                  Hypertension - Modified Hachinski
29     205  HMSTROKE                        Stroke - Modified Hachinski
30     206  HMNEURSM   Focal Neurological Symptoms - Modified Hachinski
31     207  HMNEURSG      Focal Neurological Signs - Modified Hachinski
32     208   HMSCORE                   Total score - Modified Hachinski
0      209  PTGENDER                                             Gender
1      210   PTDOBYY                                         Birth year
2      211    PTHAND                                         Handedness
3      212   PTMARRY                                     Marital status
4      213  PTEDUCAT                                          Education
5      214       GDS                         Geriatric Depression Score
6      215   MHPSYCH                                Psychiatric history
7      216  MH2NEURL                                 Neurologic History
8      217   MH3HEAD               Head Eyes Ears Nose Throught History
9      218   MH4CARD                             Cardiovascular history
10     219   MH5RESP                                Respiratory history
11     220  MH6HEPAT                                    Hepatic history
12     221   MH7DERM            Dermatologic, Connective tissue History
13     222  MH8MUSCL                          Musculosketeletal history
14     223   MH9ENDO                                  Endocrine history
15     224  MH10GAST                           Gastrointestinal history
16     225  MH11HEMA                              Hematopoietic history
17     226  MH12RENA                                      Renal history
18     227  MH13ALLE                                  Allergies history
19     228  MH14ALCH                              Alcohol abuse history
20     229  MH15DRUG                                 Drug abuse history
21     230  MH16SMOK                                    Smoking history
22     231  MH17MALI                                 Malignancy history
23     232  MH18SURG                  Major Surgical Procedures history